import { ref } from 'vue';

export function useTutorial() {
  const tutorialConfig = ref([
    {
      target: 'main-area',
      position: 'center',
      title: '✨ Welcome to the Workflow Canvas!',
      content: "Let's build your first workflow together! I'll guide you step-by-step to create a simple yet powerful automation.",
      buttonText: "Let's Go!",
      hideArrow: true,
    },
    {
      target: '#sidebar-triggers',
      position: 'right',
      title: 'Drag & Drop Magic',
      content: "Let's start by dragging a Trigger Node onto the canvas. Try dragging the 'Timer Trigger' node now!",
      buttonText: "I've Added It!",
      highlightTarget: true,
      enforceStep: false,
      missingTargetMessage: "Please drag the 'Timer Trigger' node onto the canvas to continue.",
      media: {
        type: 'gif',
        src: '/tutorial-assets/drag-node.gif',
      },
      audioContent: '/tutorial-assets/drag-trigger-node.mp3',
    },
    {
      target: '.node.trigger',
      position: 'left',
      title: 'Customize Your Node',
      content: "Great! Now, let's configure this node. Click on it to open the editor panel and fill in the details.",
      buttonText: 'Editor Opened!',
      highlightTarget: true,
      enforceStep: false,
      missingTargetMessage: 'Please click the node to open the editor panel.',
      media: {
        type: 'gif',
        src: '/tutorial-assets/open-editor.gif',
      },
      audioContent: '/tutorial-assets/open-editor.mp3',
    },
    {
      target: '#editor-panel',
      position: 'left',
      title: 'Node Configuration Panel',
      content:
        "This is the editor panel, where you can configure and customize your nodes. Let's try adjusting the 'Schedule' dropdown to 'Every Minute'!",
      buttonText: "I've Added It!",
      highlightTarget: true,
      media: {
        type: 'gif',
        src: '/tutorial-assets/open-editor.gif',
      },
      audioContent: '/tutorial-assets/editor-panel.mp3',
    },
    {
      target: '#editor-panel .panel-header',
      position: 'left',
      title: 'Panel Header',
      content: 'This is the panel header. You can drag it to reposition the panel anywhere on your screen.',
      buttonText: 'Got it!',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .right-tabs .tab-button:nth-child(1)',
      position: 'left',
      title: 'Parameters Tab',
      content: 'Click here to view and edit the parameters of your selected node.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .right-tabs .tab-button:nth-child(2)',
      position: 'left',
      title: 'Outputs Tab',
      content: 'This tab shows the outputs generated by your node after execution.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .right-tabs .tab-button:nth-child(3)',
      position: 'left',
      title: 'Expand Panel',
      content: 'Use this button to toggle the panel between normal and full-screen modes.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .node-name',
      position: 'left',
      title: 'Node Name',
      content: 'Here you can rename your node to something meaningful.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .node-id',
      position: 'left',
      title: 'Node ID',
      content: "This is your node's unique ID. Click to copy it to your clipboard.",
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .node-type',
      position: 'left',
      title: 'Node Type',
      content: "This shows the type of node you're editing.",
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .node-description p:nth-child(1)',
      position: 'left',
      title: 'Node Description',
      content: 'This briefly explains what your node does.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .node-description p:nth-child(2)',
      position: 'left',
      title: 'Tool Documentation',
      content: 'Click here for detailed node documentation.',
      buttonText: 'Got it!',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .node-connection-status',
      position: 'left',
      title: 'Connection Status',
      content: 'This indicates whether your node is connected to the required external service.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .panel-body .parameter-wrapper',
      position: 'left',
      title: 'Input Parameters',
      content: 'Here you can configure the input parameters for your node.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .panel-body .parameter-wrapper textarea',
      position: 'left',
      title: 'Detailed Instructions',
      content: 'For some nodes, you can provide detailed instructions or scripts here.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .panel-body .parameter-wrapper select',
      position: 'left',
      title: 'Dropdown Selections',
      content: 'Use dropdowns to select predefined options for your node parameters.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: "#editor-panel .panel-body .parameter-wrapper input[type='file']",
      position: 'left',
      title: 'File Upload',
      content: 'You can upload files directly here to use as inputs for your node.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .panel-body .parameter-wrapper .checkbox-group',
      position: 'left',
      title: 'Multiple Selections',
      content: 'Select multiple options easily using checkboxes.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .panel-body .outputs-wrapper',
      position: 'left',
      title: 'Node Outputs',
      content: 'This area displays the outputs your node generates after execution.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#editor-panel .panel-body .outputs-wrapper .static-value',
      position: 'left',
      title: 'Copy Output Reference',
      content: 'Click here to copy the output reference for use in other nodes.',
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '#sidebar-actions',
      position: 'right',
      title: 'Connecting the Dots',
      content:
        "Workflows become truly powerful when nodes work together seamlessly. Let's add an Action Node next—drag one from the sidebar onto your canvas and connect it to your Trigger Node!",
      buttonText: 'Next',
      highlightTarget: true,
    },
    {
      target: '.node.trigger .connector.output',
      position: 'top',
      title: 'Connect your Nodes',
      content:
        "Hover over a node to reveal its connectors. Click and drag from the trigger node's output connector to the action node's input connector to create a connection.",
      buttonText: 'Connected!',
      highlightTarget: true,
      enforceStep: false,
      missingTargetMessage: 'Please connect the nodes to continue.',
    },
    {
      target: '.node.action .connector.input',
      position: 'top',
      title: 'Disconnect your Nodes',
      content:
        'Hover over a node to reveal its connectors. To disconnect a connection, click the input connector of the action node and drag it away from the trigger node.',
      buttonText: 'Disconnected!',
      highlightTarget: true,
      enforceStep: false,
      missingTargetMessage: 'Please disconnect the nodes to continue.',
    },
    {
      target: '#workflow-magic-button',
      position: 'bottom',
      title: '✨ AI Magic: Instant Workflow ✨',
      content: 'Want to see something amazing? Describe your workflow idea, and our AI will build it instantly!',
      buttonText: 'Try AI Magic',
      showSkipButton: true,
      skipButtonText: 'Skip for Now',
      simulateClick: true,
      highlightTarget: true,
      enforceStep: false,
    },
    {
      target: '#save-workflow',
      position: 'bottom',
      title: 'Save Your Creation',
      content: 'Your workflow is ready! Click here to save your masterpiece for future use.',
      buttonText: 'Saved!',
      highlightTarget: true,
    },
    {
      target: '#workflow-engine-toggle',
      position: 'bottom',
      title: 'Activate & Automate',
      content: "It's time to bring your workflow to life. Activate it now and watch your automation in action!",
      buttonText: 'Activated!',
      highlightTarget: true,
    },
    {
      target: 'main-area',
      position: 'center',
      title: '🎉 Congratulations!',
      content: "You've successfully built and activated your first workflow! You're now ready to explore more powerful automations.",
      buttonText: 'Finish Tutorial',
      // showSkipButton: true,
      // skipButtonText: 'Finish Tutorial',
    },
  ]);

  const startTutorial = ref(false);
  const currentStep = ref(0);

  const onTutorialClose = () => {
    startTutorial.value = false;
    currentStep.value = 0;
  };

  const nextStep = () => {
    if (currentStep.value < tutorialConfig.value.length - 1) {
      currentStep.value++;
    } else {
      onTutorialClose();
    }
  };

  const initializeTutorial = () => {
    startTutorial.value = true;
    currentStep.value = 0;
  };

  return {
    tutorialConfig,
    startTutorial,
    currentStep,
    onTutorialClose,
    nextStep,
    initializeTutorial,
  };
}
