import { describe,it,expect,beforeEach,afterEach } from 'vitest';
import sqlite3 from 'sqlite3';
import { initializeLearningSchema } from '../../models/database/learningSchema.js';
import { LearningCoordinator } from './LearningCoordinator.js';
import { executeWithLearning } from './learningRuntime.js';
import { validateEvent, canonicalCandidate, hash } from './learningContract.js';

let db, service, now;
const DAY=86400000, USER='account-a', OTHER='account-b';
beforeEach(async()=>{db=await new Promise((resolve,reject)=>{const c=new sqlite3.Database(':memory:',e=>e?reject(e):resolve(c));});await initializeLearningSchema(db);now=20*DAY;service=new LearningCoordinator(db,{clock:()=>now});});
afterEach(async()=>{await service.queue;await new Promise(resolve=>db.close(resolve));});
async function event(index,outcome='failed',trialId=null){const work=await service.work(USER,'agent','run-'+index);await service.append(USER,work.id,{eventKey:'call-'+index,type:'tool_outcome',capability:'read_file',outcome,errorKind:outcome==='failed'?'timeout':null,trialId,occurredAt:now-1000,payload:{attempts:1}});return work;}
async function seed(){for(let i=0;i<20;i++)await event(i,i<8?'failed':'succeeded');return (await service.summary(USER)).findings[0];}
async function approve(){const f=await seed();return service.approve(USER,f.id,{revision:f.revision,candidateHash:f.candidate_hash});}

describe('one measured improvement lifecycle',()=>{
 it('adds schema idempotently and preserves unrelated user tables',async()=>{await service.run('CREATE TABLE memories(id TEXT)');await service.run("INSERT INTO memories VALUES('keep')");await initializeLearningSchema(db);expect(await service.get('SELECT * FROM memories')).toEqual({id:'keep'});});
 it('collapses recurrence and replay, scopes evidence, and keeps completion separate from verification',async()=>{const w=await event(1);await event(1);await event(2);await event(3);const s=await service.summary(USER);expect(s.findings).toHaveLength(1);expect(s.findings[0].occurrences).toBe(3);expect(s.findings[0].independent_runs).toBe(3);expect(s.findings[0].candidate).not.toBeNull();expect((await service.summary(OTHER)).findings).toEqual([]);await service.finishWork(USER,w.id,'completed');expect((await service.owned('learning_work',w.id,USER)).verification).toBe('unknown');await service.finishWork(USER,w.id,'running');expect((await service.owned('learning_work',w.id,USER)).state).toBe('completed');});
 it('rejects malformed events, unknown fields, unsafe candidates and cross-account evidence',async()=>{const w=await event(1);expect(()=>validateEvent({eventKey:'array',type:'work_state',occurredAt:1,payload:[]})).toThrow();expect(()=>validateEvent({eventKey:'x',type:'tool_outcome',occurredAt:1,payload:{secret:'no'}})).toThrow();expect(()=>canonicalCandidate('send_email','timeout')).toThrow();await expect(service.append(OTHER,w.id,{eventKey:'x',type:'work_state',occurredAt:now})).rejects.toMatchObject({status:404});});
 it('hash-binds approval and rejects stale revisions, insufficient baseline, overlapping changes',async()=>{await event(1);await event(2);await event(3);let f=(await service.summary(USER)).findings[0];await expect(service.approve(USER,f.id,{revision:f.revision,candidateHash:f.candidate_hash})).rejects.toThrow('insufficient_baseline');for(let i=4;i<=20;i++)await event(i,'succeeded');f=(await service.summary(USER)).findings[0];await expect(service.approve(USER,f.id,{revision:1,candidateHash:f.candidate_hash})).rejects.toThrow('stale_finding');await expect(service.approve(USER,f.id,{revision:f.revision,candidateHash:'wrong'})).rejects.toThrow('candidate_changed');const t=await service.approve(USER,f.id,{revision:f.revision,candidateHash:f.candidate_hash});expect(t.state).toBe('watching');await expect(service.approve(OTHER,f.id,{revision:f.revision,candidateHash:f.candidate_hash})).rejects.toMatchObject({status:404});});
 it('reviews persisted deadlines after a new coordinator is constructed; unexposed traffic cannot promote',async()=>{const t=await approve();now+=8*DAY;const restarted=new LearningCoordinator(db,{clock:()=>now});await restarted.reviewDue();const row=await restarted.owned('learning_trials',t.id,USER);expect(row.state).toBe('reviewed');expect(row.result.verdict).toBe('inconclusive');expect(await restarted.policyFor(USER,'read_file')).toBeNull();await expect(restarted.keep(USER,t.id,row.revision,row.candidate_hash)).rejects.toThrow('promotion_not_supported');});
 it('measures only exposed cohorts, requires owner keep, activates and actually undoes policy',async()=>{const t=await approve();now+=DAY;for(let i=100;i<125;i++)await event(i,'succeeded',t.id);now+=7*DAY;await service.reviewDue();let reviewed=await service.owned('learning_trials',t.id,USER);expect(reviewed.result.verdict).toBe('supported');expect(reviewed.result.candidate.eligible).toBe(25);expect(await service.policyFor(USER,'read_file')).toBeNull();await service.keep(USER,t.id,reviewed.revision,t.candidate_hash);expect((await service.policyFor(USER,'read_file')).id).toBe(t.id);const active=await service.owned('learning_trials',t.id,USER);expect(await service.undo(USER,t.id,active.revision)).toEqual({state:'reverted',restored:true});expect(await service.policyFor(USER,'read_file')).toBeNull();expect((await service.summary(USER)).policies[0].state).toBe('reverted');});
 it('pause blocks new effects but never loses an outstanding review',async()=>{const t=await approve();await service.setPaused(USER,true);expect(await service.policyFor(USER,'read_file')).toBeNull();now+=8*DAY;await service.reviewDue();expect((await service.owned('learning_trials',t.id,USER)).state).toBe('reviewed');});
 it('dismissal stays dismissed when evidence repeats',async()=>{const f=await seed();await service.dismiss(USER,f.id,f.revision);await event(50);expect((await service.summary(USER)).findings[0].state).toBe('dismissed');expect((await service.summary(USER)).findings[0].candidate).toBeNull();});
 it('runtime executes only one approved transient read retry and records measured exposure',async()=>{const t=await approve();let calls=0;now+=DAY;const result=await executeWithLearning({userId:USER,executionId:'runtime',callId:'call',capability:'read_file',coordinator:service,execute:async()=>++calls===1?{success:false,error:'ETIMEDOUT'}:{success:true,content:'ok'}});expect(calls).toBe(2);expect(result.success).toBe(true);const exposure=await service.all("SELECT * FROM learning_events WHERE trial_id=? AND type='policy_exposure'",[t.id]);expect(exposure).toHaveLength(1);const outcome=await service.get("SELECT * FROM learning_events WHERE trial_id=? AND type='tool_outcome'",[t.id]);expect(JSON.parse(outcome.payload_json).recovered).toBe(true);expect(outcome.outcome).toBe('succeeded');});
 it('never retries auth failures, irreversible tools, revoked policy or ownership denial',async()=>{await approve();let n=0;await executeWithLearning({userId:USER,executionId:'auth',callId:'call',capability:'read_file',coordinator:service,execute:async()=>{n++;return {success:false,error:'401 unauthorized'};}});expect(n).toBe(1);await executeWithLearning({userId:USER,executionId:'mail',callId:'call',capability:'send_email',coordinator:service,execute:async()=>{n++;return {success:false,error:'ETIMEDOUT'};}});expect(n).toBe(2);await expect(executeWithLearning({userId:USER,executionId:'denied',callId:'call',capability:'read_file',coordinator:service,execute:async()=>({success:false,error:'ETIMEDOUT'}),assertCurrent:()=>{throw new Error('revoked');}})).rejects.toThrow('revoked');});
 it('kept policies are automatically removed after a statistically separated regression',async()=>{
   const t=await approve();now+=DAY;for(let i=100;i<150;i++)await event(i,'succeeded',t.id);now+=7*DAY;await service.reviewDue();let reviewed=await service.owned('learning_trials',t.id,USER);await service.keep(USER,t.id,reviewed.revision,t.candidate_hash);
   now+=DAY;for(let i=200;i<260;i++)await event(i,'failed',t.id);await service.reviewDue();expect(await service.policyFor(USER,'read_file')).toBeNull();expect((await service.owned('learning_trials',t.id,USER)).state).toBe('reverted');
 });
 it('unfinished exposed calls and malformed measurements block promotion',async()=>{
   const t=await approve();now+=DAY;for(let i=100;i<150;i++)await event(i,'succeeded',t.id);
   const work=await service.work(USER,'agent','interrupted');await service.append(USER,work.id,{eventKey:'exposure:interrupted:call',type:'policy_exposure',capability:'read_file',outcome:'failed',errorKind:'timeout',trialId:t.id,occurredAt:now,payload:{candidateHash:t.candidate_hash}});
   expect(()=>validateEvent({eventKey:'bad',type:'tool_outcome',capability:'read_file',outcome:'failed',occurredAt:1,payload:{durationMs:-1}})).toThrow('invalid_measurement');now+=7*DAY;await service.reviewDue();expect((await service.owned('learning_trials',t.id,USER)).result.verdict).toBe('inconclusive');
 });
 it('two racing approvals produce only one trial and transition receipt',async()=>{
   const f=await seed();const results=await Promise.allSettled([1,2].map(()=>service.approve(USER,f.id,{revision:f.revision,candidateHash:f.candidate_hash})));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await service.all('SELECT * FROM learning_trials')).length).toBe(1);expect((await service.all("SELECT * FROM learning_events WHERE type='trial_state'")).length).toBe(1);
 });

});
