<template><header class="m-dashboard-overview"><small>SYSTEM AT A GLANCE</small><h1>Your work.<br><span>All in view.</span></h1><div class="m-dashboard-metrics"><button v-for="metric in metrics" :key="metric.label" type="button" @click="$emit('navigate',metric.screen)"><small>{{metric.label}}</small><strong>{{metric.value ?? 0}}</strong><i class="fas fa-chevron-right" aria-hidden="true"></i></button></div></header></template>
<script setup>
import { computed } from 'vue';
const props=defineProps({goals:{type:Object,default:()=>({})},agents:{type:Object,default:()=>({})},workflows:{type:Object,default:()=>({})},runs:{type:Object,default:()=>({})}});defineEmits(['navigate']);
const metrics=computed(()=>[{label:'Active goals',value:props.goals.active,screen:'GoalsScreen'},{label:'Active agents',value:props.agents.active,screen:'AgentsScreen'},{label:'Active workflows',value:props.workflows.active,screen:'WorkflowsScreen'},{label:'Runs today',value:props.runs.daily,screen:'TracesScreen'}]);
</script>
<style scoped>
.m-dashboard-overview{padding:20px 15px 0;box-sizing:border-box;width:100%;flex:none}.m-dashboard-overview>small{font:10px var(--font-family-mono,monospace);letter-spacing:.14em;color:var(--color-text-muted)}h1{font-size:35px;font-weight:500;line-height:1.08;letter-spacing:-.04em;margin:17px 0 21px;color:var(--color-text)}h1 span{color:var(--text-green)}.m-dashboard-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.m-dashboard-metrics button{display:block;position:relative;text-align:left;min-height:100px;background:var(--color-darker-0);border:1px solid var(--terminal-border-color);border-radius:13px;padding:15px;color:var(--color-text);cursor:pointer}.m-dashboard-metrics small{font:10px var(--font-family-mono,monospace);color:var(--color-text-muted)}.m-dashboard-metrics strong{display:block;font:500 28px/1.1 inherit;margin-top:10px;font-size:28px}.m-dashboard-metrics i{position:absolute;right:14px;bottom:19px;font-size:11px;color:var(--color-text-muted)}
</style>
