import { describe, it, expect } from 'vitest';
import { mount } from '@vue/test-utils';
import MobileDirectory from './MobileDirectory.vue';
import { settingsDirectory, appsDirectory } from './sectionDirectories.js';
const settings=settingsDirectory.flatMap(g=>g.items);
describe('shared desktop/mobile section directories',()=>{
 it('keeps all eighteen Settings sections plus subordinate screens',()=>{const sections=settings.filter(i=>!i.screen);expect(new Set(sections.map(s=>s.id)).size).toBe(18);expect(sections.map(s=>s.id)).not.toContain('notifications');expect(sections.map(s=>s.id)).toContain('usage');expect(settings.filter(i=>i.screen).map(i=>i.screen)).toEqual(['LearningScreen']);});
 it('preserves the actual Apps navigation IDs without a redundant Vault, and no AI models',()=>{expect(appsDirectory.map(g=>g.items.map(i=>i.id))).toEqual([['apps','email-server','webhooks','mcp-servers','plugins','oauth']]);expect(appsDirectory[0].items.find(i=>i.id==='plugins').screen).toBe('PluginsScreen');expect(appsDirectory.flatMap(g=>g.items).some(i=>i.id==='providers'||i.id==='api-keys')).toBe(false);});
 it('groups Settings into General, Account, Advanced and Help, none with a single page, no row twice',()=>{expect(settingsDirectory.map(g=>g.label)).toEqual(['General','Account','Advanced','Help']);expect(settingsDirectory[0].items[0].id).toBe('providers');expect(settingsDirectory.find(g=>g.label==='Advanced').items.map(i=>i.id)).toEqual(['navigation','phone-access','connection','backup','reset']);for(const g of settingsDirectory)expect(g.items.length,g.label).toBeGreaterThan(1);const ids=settings.map(i=>i.id);expect(new Set(ids).size).toBe(ids.length);expect(settings.find(i=>i.id==='general').label).toBe('Sign in / out');});
 it('emits the source definition rather than inventing routes',async()=>{const w=mount(MobileDirectory,{props:{title:'Settings',groups:settingsDirectory}});await w.findAll('.m-directory-item').find(e=>e.text().includes('Learning')).trigger('click');expect(w.emitted('select')[0][0].screen).toBe('LearningScreen');});
 it('filters grouped items and shows a useful empty state',async()=>{const w=mount(MobileDirectory,{props:{title:'Apps',groups:appsDirectory}});await w.find('input').setValue('MCP');expect(w.findAll('.m-directory-item')).toHaveLength(1);await w.find('input').setValue('nothing');expect(w.find('.m-directory-empty').exists()).toBe(true);});
});
