<template>
<section class="m-directory" :data-mobile-view="viewId"><h1>{{ title }}</h1><label class="m-directory-search"><i class="fas fa-search" aria-hidden="true"></i><input v-model="query" :placeholder="'Find in ' + title" :aria-label="'Find in ' + title" /></label><section v-for="group in filtered" :key="group.label" class="m-directory-group"><h2>{{ group.label }}</h2><button v-for="item in group.items" :key="item.id" type="button" class="m-directory-item" @click="$emit('select', item)"><span class="m-directory-icon"><i :class="item.icon || 'fas fa-cog'" aria-hidden="true"></i></span><span><strong>{{ item.label }}</strong><small v-if="item.description">{{ item.description }}</small></span><small v-if="item.pro" class="m-directory-badge">PRO</small><i class="fas fa-chevron-right" aria-hidden="true"></i></button></section><p v-if="!filtered.length" class="m-directory-empty">No matching settings. Try another search.</p></section>
</template>
<script setup>
import { ref, computed } from 'vue';
const props=defineProps({title:String,viewId:String,groups:{type:Array,default:()=>[]}});defineEmits(['select']);const query=ref('');
const filtered=computed(()=>props.groups.map(group=>({...group,items:group.items.filter(item=>(item.label+' '+(item.description||'')).toLowerCase().includes(query.value.toLowerCase()))})).filter(g=>g.items.length));
</script>
<style scoped>
section,header,label,article,button,input,span,div{box-sizing:border-box}
.m-directory{flex:1;min-height:0;overflow:auto;padding:20px 15px 30px;box-sizing:border-box;width:100%;background:var(--color-background);color:var(--color-text)}h1{font-size:23px;font-weight:600;letter-spacing:-.03em;margin:0 0 20px}.m-directory-search{width:100%;min-width:0;display:flex;align-items:center;gap:10px;border:1px solid var(--terminal-border-color);border-radius:11px;min-height:48px;padding:0 12px;color:var(--color-text-muted)}input{width:100%;min-width:0;font:16px inherit;color:var(--color-text);background:none;border:0;min-height:44px;font-size:16px;outline-offset:2px}.m-directory-group h2{font:10px var(--font-family-mono,monospace);letter-spacing:.13em;text-transform:uppercase;color:var(--color-text-muted);margin:25px 0 7px}.m-directory-item{width:100%;display:flex;align-items:center;gap:12px;text-align:left;min-height:72px;border:0;border-bottom:1px solid var(--terminal-border-color);background:none;color:var(--color-text);padding:12px 0;font:inherit;cursor:pointer}.m-directory-icon{width:38px;height:38px;display:grid;place-items:center;border-radius:11px;background:var(--color-darker-0);border:1px solid var(--terminal-border-color);color:var(--text-green);flex:none}.m-directory-item>span:nth-child(2){flex:1}.m-directory-item strong{display:block;font-size:14px;font-weight:500}.m-directory-item small{display:block;font-size:11px;line-height:1.5;color:var(--color-text-muted);margin-top:4px}.m-directory-item>i{font-size:12px;color:var(--color-text-muted)}.m-directory-item .m-directory-badge{font-size:8px;color:var(--text-yellow);background:var(--color-darker-0);padding:4px;border-radius:5px}.m-directory-empty{padding:30px 8px;text-align:center;color:var(--color-text-muted);font-size:13px}
</style>
