/**
 * Editing the latest assistant reply in place.
 *
 * WHY ONLY THE LATEST REPLY, AND ONLY ITS CLOSING TEXT
 *
 * Prompt caching stores the INPUT of a request, never its output. A reply's
 * closing text (the words after its last tool call, or the whole reply when it
 * used no tools) was generated by the final request of the turn and has never
 * been sent back to the provider, so it is not in any cache. The next turn
 * sends it fresh whether or not it was edited: an edit there costs nothing.
 *
 * Text written BEFORE a tool call is different. The tool loop re-sent it as
 * input on every later round of that turn, so it sits inside a cached prefix;
 * changing it would invalidate that turn's rounds. And any earlier reply is
 * inside the cross-turn prefix. Both are therefore out of scope by design.
 *
 * The edit is silent: the model reads the edited text as what it said. No
 * marker, no original kept — by product decision.
 *
 * Shared by both chat stores (chat.js, chatUnified.js) and MessageItem, so the
 * rule for "what may be edited" exists exactly once.
 */

const CONVERSATIONAL_ROLES = new Set(['user', 'assistant']);

/**
 * The closing text of an assistant reply: its last text part, provided no tool
 * call follows it. Null when the message is not an assistant reply, ends on a
 * tool call, or has no words to edit.
 */
export function closingText(message) {
  if (!message || message.role !== 'assistant') return null;
  const parts = Array.isArray(message.contentParts) ? message.contentParts : [];
  if (parts.length === 0) {
    const content = typeof message.content === 'string' ? message.content : '';
    return content.trim() ? content : null;
  }
  const last = parts[parts.length - 1];
  if (!last || last.type !== 'text' || typeof last.text !== 'string' || !last.text.trim()) return null;
  return last.text;
}

/**
 * Id of the one message that may be edited, or null.
 *
 * It must be the last conversational message (non-conversational rows such as
 * goal-event cards or the compaction marker are skipped over — they are not
 * turns), it must answer something (a user turn precedes it, which excludes a
 * welcome message), and it must not be a provider-setup prompt.
 */
export function editableReplyId(messages) {
  if (!Array.isArray(messages)) return null;
  for (let i = messages.length - 1; i >= 0; i--) {
    const message = messages[i];
    if (!message || !CONVERSATIONAL_ROLES.has(message.role)) continue;
    if (message.role !== 'assistant') return null;
    if (message.showProviderSetup) return null;
    if (closingText(message) === null) return null;
    const answersSomething = messages.slice(0, i).some((m) => m && m.role === 'user');
    return answersSomething ? message.id : null;
  }
  return null;
}

/**
 * Replace a reply's closing text in place. Returns the text it replaced.
 *
 * `content` and `contentParts` are two views of the same words and must stay
 * in step: buildChatHistory reads contentParts for tool-using replies and
 * content for plain ones. The closing text is always the tail of `content`
 * (the stream appends to both), so the tail is swapped and any separator the
 * earlier text used is preserved.
 *
 * Saved reasoning is dropped: it reasoned toward the old words, and providers
 * that replay it (DeepSeek, Kimi, Z.AI) would be fed a justification for text
 * that no longer exists.
 */
export function applyReplyEdit(message, newText) {
  const previousText = closingText(message);
  if (previousText === null) throw new Error('applyReplyEdit: message has no editable closing text');
  if (typeof newText !== 'string' || !newText.trim()) throw new Error('applyReplyEdit: new text is empty');

  const parts = Array.isArray(message.contentParts) ? message.contentParts : [];
  if (parts.length > 0) {
    // Replace the part object rather than mutate it: MessageItem memoises
    // rendered parts on identity.
    parts.splice(parts.length - 1, 1, { ...parts[parts.length - 1], text: newText });
  }

  const content = typeof message.content === 'string' ? message.content : '';
  if (parts.length === 0) {
    message.content = newText;
  } else if (content.endsWith(previousText)) {
    message.content = content.slice(0, content.length - previousText.length) + newText;
  } else {
    message.content = parts.filter((p) => p.type === 'text').map((p) => p.text || '').join('');
  }

  delete message.reasoning;
  delete message.reasoning_content;
  return previousText;
}
