import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {pathToFileURL, fileURLToPath} from 'node:url';const require=createRequire(import.meta.url);const puppeteer=require('puppeteer');const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');const evidence=process.env.AGNT_MOBILE_EVIDENCE_DIR;if(!evidence)throw new Error('Set AGNT_MOBILE_EVIDENCE_DIR to a new evidence directory');fs.mkdirSync(evidence,{recursive:true});const {createServer}=await import(pathToFileURL(root+'/node_modules/vite/dist/node/index.js'));const {default:vue}=await import(pathToFileURL(root+'/node_modules/@vitejs/plugin-vue/dist/index.mjs'));const {aliases}=await import(pathToFileURL(root+'/build/aliases.js'));const server=await createServer({configFile:false,root,base:'/',plugins:[vue()],resolve:{alias:aliases},server:{host:'127.0.0.1',port:0,fs:{allow:[root,path.dirname(root)]}}});await server.listen();const port=server.httpServer.address().port;const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-first-run'],defaultViewport:{width:390,height:844,deviceScaleFactor:1,isMobile:true,hasTouch:true}});const errors=[],blocked=[];try{const page=await browser.newPage();await page.setRequestInterception(true);page.on('request',r=>{const url=r.url();if(url.startsWith('data:')||url.startsWith('blob:')||url.startsWith('http://127.0.0.1:'+port))r.continue();else{blocked.push(url);if(url.includes('fonts.googleapis.com'))r.respond({status:200,contentType:'text/css',body:''});else r.abort();}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:'+port+'/_harness/mobile.html',{waitUntil:'networkidle2',timeout:60000});await new Promise(r=>setTimeout(r,2500));console.log(JSON.stringify({errors,blocked,body:await page.$eval('body',el=>el.innerText.slice(0,5500)),fixture:await page.evaluate(()=>!!window.MOBILE_FIXTURE)},null,2));await page.waitForSelector('.left-panel-component .search-input',{timeout:15000});
await page.waitForSelector('.right-panel-component .insp',{timeout:15000});
const checks=[];
await page.evaluate(()=>{window.__themeWrites=[];MOBILE_FIXTURE.store.subscribe(m=>{if(m.type.startsWith('theme/'))window.__themeWrites.push({type:m.type,mobile:MOBILE_FIXTURE.mobile.value});});});const check=async(name,fn)=>{try{checks.push({name,pass:!!(await fn())});}catch(e){checks.push({name,pass:false,error:e.message});}};
await check('Saved Chats visible',()=>page.$eval('[data-mobile-panel="left"]',e=>e.getBoundingClientRect().width>=44));
await page.click('[data-mobile-panel="left"]');await new Promise(r=>setTimeout(r,400));
await check('Only left panel open',()=>page.evaluate(()=>document.querySelector('.left-panel-component').classList.contains('mobile-panel-visible')&&!document.querySelector('.right-panel-component').classList.contains('mobile-panel-visible')));
await page.type('.left-panel-component .search-input','Design');await page.click('.left-panel-component .mobile-close-button');await page.click('[data-mobile-panel="left"]');
await check('History search retained',()=>page.$eval('.left-panel-component .search-input',e=>e.value==='Design'));
await page.click('.left-panel-component .output-content');await new Promise(r=>setTimeout(r,700));
await check('Selected conversation and overlay close',()=>page.evaluate(()=>MOBILE_FIXTURE.store.state.chat.activeConversationId==='conversation-two'&&!document.querySelector('.mobile-panel-visible')));
await page.type('.chat-input-textarea','Draft two retained');await page.click('[data-mobile-panel="right"]');await new Promise(r=>setTimeout(r,400));
await check('Context measurements present',()=>page.$eval('.right-panel-component',e=>e.innerText.toLowerCase().includes('context & cost')&&!!e.querySelector('.monitoring-panel')));
await check('Main content inert',()=>page.$eval('.main-panel[inert]',e=>e.inert));
await page.keyboard.press('Escape');await page.click('[data-mobile-panel="left"]');
await page.$eval('.search-input',e=>{e.value='';e.dispatchEvent(new Event('input',{bubbles:true}));});await new Promise(r=>setTimeout(r,100));
await page.evaluate(()=>MOBILE_FIXTURE.switch('one'));await new Promise(r=>setTimeout(r,500));
await check('Draft isolated',()=>page.$eval('.chat-input-textarea',e=>e.value===''));
await page.evaluate(()=>MOBILE_FIXTURE.switch('two'));await new Promise(r=>setTimeout(r,400));
await check('Draft restored',()=>page.$eval('.chat-input-textarea',e=>e.value==='Draft two retained'));
await page.evaluate(()=>{const buttons=[...document.querySelectorAll('.chat-provider-button')];buttons.find(b=>b.getClientRects().length&&!b.closest('[inert]'))?.click();});await new Promise(r=>setTimeout(r,250));
await check('Provider picker fits',()=>page.$eval('.chat-provider-selector',e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight+1;}));
await page.keyboard.press('Escape');await page.evaluate(()=>document.body.click());
await page.setViewport({width:1280,height:900,isMobile:true,hasTouch:true});await new Promise(r=>setTimeout(r,450));
await check('Desktop draft and chrome retained',()=>page.evaluate(()=>document.querySelector('.chat-input-textarea').value==='Draft two retained'&&!document.querySelector('.mobile-screen-actions')&&!document.querySelector('.cv-mobile-menu')));
await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await new Promise(r=>setTimeout(r,450));
await page.click('.cv-mobile-menu');await new Promise(r=>setTimeout(r,100));
await check('Navigation labels present',()=>page.$eval('.cv-sidebar',e=>['Chat','Dashboard','Goals','Files','Settings'].every(s=>e.innerText.includes(s))));
await page.screenshot({path:path.join(evidence,'navigation.png')});
await page.click('.cv-mobile-nav-close');
await page.screenshot({path:path.join(evidence,'chat.png')});

await check('Streaming starts through real chat service',async()=>{await page.$eval('.chat-input-textarea',e=>{e.value='Verify this mobile request';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.click('.chat-send-button');await new Promise(r=>setTimeout(r,350));return page.evaluate(()=>MOBILE_FIXTURE.requests.some(r=>r.method==='POST'&&r.path.includes('orchestrator')));});
await check('Stop control replaces send',()=>page.evaluate(()=>!!document.querySelector('.chat-stop-button, [aria-label="Stop generating"], .chat-stop-btn')));
await page.click('.chat-stop-button');await new Promise(r=>setTimeout(r,150));
await check('Stop aborts the running conversation',()=>page.evaluate(()=>!MOBILE_FIXTURE.store.state.chat.isStreaming&&!!document.querySelector('.chat-send-button')));
await new Promise(r=>setTimeout(r,1500));
await check('Streamed answer rendered',()=>page.evaluate(()=>document.body.innerText.includes('Verified response segment.')));
await page.click('[data-mobile-panel="left"]');
await page.$eval('.left-panel-component .search-input',e=>{e.value='Research-filter';e.dispatchEvent(new Event('input',{bubbles:true}));});
await page.evaluate(()=>MOBILE_FIXTURE.store.commit('theme/SET_SHOW_LEFT_PANEL',false));
await page.setViewport({width:1280,height:900,isMobile:true,hasTouch:true});await new Promise(r=>setTimeout(r,300));
await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await new Promise(r=>setTimeout(r,300));await page.click('[data-mobile-panel="left"]');
await check('Hidden desktop panel retains mobile search',()=>page.$eval('.left-panel-component .search-input',e=>e.value==='Research-filter'));
await page.click('.left-panel-component .mobile-close-button');
await check('Mobile close leaves desktop visibility false',()=>page.evaluate(()=>MOBILE_FIXTURE.store.getters['theme/showLeftPanel']===false));
await check('Group menu accessible by touch button',async()=>{await page.click('[data-mobile-panel="left"]');await page.evaluate(()=>{const b=[...document.querySelectorAll('.view-seg-btn')].find(b=>b.textContent.includes('Groups'));b.click();});await new Promise(r=>setTimeout(r,100));return page.$eval('.mobile-group-menu',e=>e.getBoundingClientRect().height>=44);});
await page.click('.mobile-group-menu');await new Promise(r=>setTimeout(r,100));
await check('Group actions fit phone',()=>page.$eval('.action-menu',e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1;}));
await page.evaluate(()=>document.body.click());await page.click('.left-panel-component .mobile-close-button');
await check('Tools picker fits and retains channel',async()=>{await page.click('.chat-tools-button');await new Promise(r=>setTimeout(r,300));return page.$eval('.chat-tool-selector',e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1;});});
await page.keyboard.press('Escape');
await check('New chat asks before clearing',async()=>{await page.evaluate(()=>[...document.querySelectorAll('.mobile-screen-actions button')].find(b=>b.textContent.includes('New chat')).click());await new Promise(r=>setTimeout(r,180));return page.evaluate(()=>!!document.querySelector('.modal-overlay')&&MOBILE_FIXTURE.store.state.chat.activeConversationId==='conversation-two');});
await page.keyboard.press('Escape');await new Promise(r=>setTimeout(r,100));
await check('Cancel preserves conversation',()=>page.evaluate(()=>MOBILE_FIXTURE.store.state.chat.activeConversationId==='conversation-two'&&!document.querySelector('.modal-overlay')));
await check('No compact geometry writes',()=>page.evaluate(()=>!window.__themeWrites.some(t=>t.mobile&&/WIDTH|SIZED/.test(t.type))));
const matrix=[];
for(const width of [320,360,390,430,800,801,1280]){await page.setViewport({width,height:844,isMobile:true,hasTouch:true});await new Promise(r=>setTimeout(r,250));matrix.push(await page.evaluate(()=>{const main=document.querySelector('.chat-screen-wrapper .main-panel'),composer=document.querySelector('.input-container'),nav=document.querySelector('.cv-mobile-menu');const r=composer.getBoundingClientRect();return{width:innerWidth,pageOverflow:document.documentElement.scrollWidth-innerWidth,composer:{left:r.left,right:r.right,bottom:r.bottom},mobileButton:!!nav};}));}
await page.setViewport({width:390,height:500,isMobile:true,hasTouch:true});await new Promise(r=>setTimeout(r,350));
await check('Keyboard-height composer above visible bottom',()=>page.$eval('.input-container',e=>e.getBoundingClientRect().bottom<=visualViewport.height+2));
await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await page.evaluate(()=>MOBILE_FIXTURE.store.commit('theme/SET_SHOW_LEFT_PANEL',true));
console.log('MATRIX',JSON.stringify(matrix));
console.log(JSON.stringify({checks,errors,apiRequests:await page.evaluate(()=>MOBILE_FIXTURE.requests)},null,2));
fs.writeFileSync(path.join(evidence,'browser-complete.json'),JSON.stringify({checks,errors,matrix},null,2),{flag:'wx'});
if(checks.some(c=>!c.pass)||errors.length||matrix.some(m=>m.pageOverflow>0))process.exitCode=1;
}finally{await browser.close();await server.close();}
