import { describe,it,expect,vi } from 'vitest';
import { DatabaseSync } from 'node:sqlite';
import { collectActivationMilestones,syncActivationMilestones } from './ActivationMilestoneService.js';
import { activationMilestoneHandler } from '../routes/activationMilestoneHandler.js';
function fixture(){const raw=new DatabaseSync(':memory:');raw.exec(`CREATE TABLE agent_executions(id TEXT,user_id TEXT,status TEXT,error TEXT,parent_execution_id TEXT,origin TEXT,start_time TEXT,end_time TEXT);CREATE TABLE workflow_executions(id TEXT,user_id TEXT,status TEXT,start_time TEXT,end_time TEXT);`);const db={run(sql,args,cb){try{const result=raw.prepare(sql).run(...args);cb.call({changes:result.changes},null);}catch(e){cb(e);}},get(sql,args,cb){try{cb(null,raw.prepare(sql).get(...args));}catch(e){cb(e);}}};return {raw,db};}
const user='account_0001',start='2026-09-01T00:00:00.000Z',end='2026-09-01T00:01:00.000Z';
function seed(raw){for(const [id,owner,status,error,parent,origin]of [['failed',user,'failed','error',null,'chat'],['stopped',user,'stopped',null,null,'chat'],['child',user,'completed',null,'parent','chat'],['test',user,'completed',null,null,'test'],['foreign','someone_else','completed',null,null,'chat'],['successful',user,'completed',null,null,'chat']])raw.prepare('INSERT INTO agent_executions VALUES(?,?,?,?,?,?,?,?)').run(id,owner,status,error,parent,origin,start,end);raw.prepare('INSERT INTO workflow_executions VALUES(?,?,?,?,?)').run('workflow',user,'completed',start,'2026-09-01T00:02:00.000Z');}
describe('activation milestones',()=>{
 it('selects actual successful roots by owner; never failures, child runs or test runs',async()=>{const f=fixture();try{seed(f.raw);const rows=await collectActivationMilestones(f.db,user);expect(rows.map(r=>r.name)).toEqual(['first_agent_completed','first_workflow_completed','first_run_completed']);expect(rows[0].execution_id).toBe('successful');expect(rows[2].occurred_at).toBe(end);}finally{f.raw.close();}});
 it('durable retry preserves original time and sends once even across repeated syncs',async()=>{const f=fixture();let time=Date.parse('2026-09-07T00:00:00Z');try{seed(f.raw);const fetchImpl=vi.fn().mockResolvedValueOnce({ok:false,status:503}).mockResolvedValue({ok:true,json:async()=>({success:true})});const options={db:f.db,userId:user,token:'test',appVersion:'0.6.6',enabled:true,now:()=>time,fetchImpl};await expect(syncActivationMilestones(options)).rejects.toThrow('HTTP 503');time+=61000;expect((await syncActivationMilestones(options)).sent).toBe(3);expect((await syncActivationMilestones(options)).sent).toBe(0);expect(fetchImpl).toHaveBeenCalledTimes(4);for(const [,request]of fetchImpl.mock.calls){const body=JSON.parse(request.body);expect(body.occurred_at.startsWith('2026-09-01')).toBe(true);expect(body).not.toHaveProperty('user_id');expect(Object.keys(body.meta).sort()).toEqual(['app_version','execution_id','source_event_id']);}expect(f.raw.prepare('SELECT COUNT(*) n FROM activation_milestone_outbox WHERE acknowledged_at IS NOT NULL').get().n).toBe(3);}finally{f.raw.close();}});
 it('disabled telemetry reads no execution data and sends nothing',async()=>{const fetchImpl=vi.fn();expect(await syncActivationMilestones({db:null,userId:user,token:'test',enabled:false,fetchImpl})).toEqual({enabled:false,sent:0});expect(fetchImpl).not.toHaveBeenCalled();});
 it('single-flights simultaneous account delivery',async()=>{const f=fixture();try{seed(f.raw);const fetchImpl=vi.fn().mockResolvedValue({ok:true,json:async()=>({success:true})});const options={db:f.db,userId:'singleflight',token:'test',enabled:true,fetchImpl};f.raw.exec("UPDATE agent_executions SET user_id='singleflight' WHERE id='successful';UPDATE workflow_executions SET user_id='singleflight'");await Promise.all([syncActivationMilestones(options),syncActivationMilestones(options)]);expect(fetchImpl).toHaveBeenCalledTimes(3);}finally{f.raw.close();}});
 it('HTTP handler rejects anonymous and ignores body ownership',async()=>{const sync=vi.fn().mockResolvedValue({sent:1});const handler=activationMilestoneHandler({db:{},appVersion:'test',sync});const res={status:vi.fn().mockReturnThis(),json:vi.fn().mockReturnThis()};await handler({user:{},headers:{},body:{}},res);expect(res.status).toHaveBeenCalledWith(401);await handler({user:{userId:user,isAuthenticated:true},headers:{authorization:'Bearer real'},body:{enabled:true,userId:'forged'}},res);expect(sync.mock.calls[0][0].userId).toBe(user);});
});
