import {describe,it,expect,vi} from 'vitest';import {ApprovedPublication} from './ApprovedPublication.js';
const input={actorId:'alice',teamId:'team',collectionId:'collection',kind:'agent',content:'{"name":"Reviewed"}'};
describe('approved publication boundary',()=>{
 it('uploads exactly the reviewed bytes and consumes approval',async()=>{const service=new ApprovedPublication();const preview=service.preview(input),upload=vi.fn(async()=>({id:'remote'})),authorize=vi.fn(async()=>{});await service.publish({...input,...preview},authorize,upload);expect(upload.mock.calls[0][0].bytes.toString()).toBe(input.content);expect(upload.mock.calls[0][0].idempotencyKey).toBe(preview.approvalId);await expect(service.publish({...input,...preview},authorize,upload)).rejects.toMatchObject({status:404});});
 it('refuses another actor, changed destination or changed hash before uploading',async()=>{const s=new ApprovedPublication(),p=s.preview(input),upload=vi.fn();for(const change of [{actorId:'bob'},{teamId:'other'},{collectionId:'other'},{sha256:'different'}])await expect(s.publish({...input,...p,...change},async()=>{},upload)).rejects.toBeTruthy();expect(upload).not.toHaveBeenCalled();});
 it('rechecks destination membership and expires old approvals',async()=>{let now=1;const s=new ApprovedPublication({clock:()=>now,ttlMs:10}),p=s.preview(input),upload=vi.fn();await expect(s.publish({...input,...p},async()=>{throw Object.assign(Error('Removed'),{status:403});},upload)).rejects.toMatchObject({status:403});now=12;await expect(s.publish({...input,...p},async()=>{},upload)).rejects.toMatchObject({status:404});expect(upload).not.toHaveBeenCalled();});
 it('bounds pending storage and byte size',()=>{const s=new ApprovedPublication({maxBytes:30,maxPending:1});s.preview(input);expect(()=>s.preview(input)).toThrow('Too many');expect(()=>new ApprovedPublication({maxBytes:1}).preview(input)).toThrow('too large');});
 it('rejects concurrent commits and retains the same retry identity after delivery failure',async()=>{const s=new ApprovedPublication(),p=s.preview(input);let release;const first=s.publish({...input,...p},async()=>{},()=>new Promise((_,reject)=>{release=reject;}));await Promise.resolve();await expect(s.publish({...input,...p},async()=>{},async()=>{})).rejects.toMatchObject({status:409});release(Error('Offline'));await expect(first).rejects.toThrow('Offline');const upload=vi.fn(async()=>({id:'remote'}));await s.publish({...input,...p},async()=>{},upload);expect(upload.mock.calls[0][0].idempotencyKey).toBe(p.approvalId);});
});
