import {randomUUID} from 'node:crypto';
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
export async function initializeTeamWorkspaces(repository){
 await repository.run(`CREATE TABLE IF NOT EXISTS shared_workspaces(id TEXT PRIMARY KEY,team_id TEXT NOT NULL REFERENCES teams(id),name TEXT NOT NULL,created_by TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,canvas_json TEXT NOT NULL DEFAULT '[]',archived_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`);
 await repository.run('CREATE INDEX IF NOT EXISTS shared_workspaces_team ON shared_workspaces(team_id,archived_at)');
 await repository.run(`CREATE TABLE IF NOT EXISTS shared_workspace_preferences(workspace_id TEXT NOT NULL REFERENCES shared_workspaces(id),user_id TEXT NOT NULL,is_open INTEGER NOT NULL DEFAULT 1 CHECK(is_open IN (0,1)),PRIMARY KEY(workspace_id,user_id))`);
 await repository.run(`CREATE TABLE IF NOT EXISTS shared_workspace_resources(workspace_id TEXT NOT NULL REFERENCES shared_workspaces(id),asset_id TEXT NOT NULL REFERENCES team_assets(id),PRIMARY KEY(workspace_id,asset_id))`);
}
export class TeamWorkspaceRepository {
 constructor(repository){this.repository=repository;}
 list(teamId,user){const r=this.repository;return r.transaction(async()=>{await r.member(teamId,user);return r.all('SELECT w.*,COALESCE(p.is_open,1) AS is_open FROM shared_workspaces w LEFT JOIN shared_workspace_preferences p ON p.workspace_id=w.id AND p.user_id=? WHERE w.team_id=? AND w.archived_at IS NULL ORDER BY w.created_at',[user,teamId]);});}
 create(teamId,user,name){const r=this.repository;return r.transaction(async()=>{await r.member(teamId,user,['owner','admin','member']);if(typeof name!=='string'||!name.trim()||name.length>100)fail(400,'Workspace name is required (100 characters maximum)');const id=randomUUID();await r.run('INSERT INTO shared_workspaces(id,team_id,name,created_by) VALUES(?,?,?,?)',[id,teamId,name.trim(),user]);await r.event(teamId,user,'workspace.created',id);return r.get('SELECT * FROM shared_workspaces WHERE id=?',[id]);});}
 async find(teamId,id){const row=await this.repository.get('SELECT * FROM shared_workspaces WHERE id=? AND team_id=? AND archived_at IS NULL',[id,teamId]);if(!row)fail(404,'Workspace not found');return row;}
 update(teamId,user,id,input){const r=this.repository;return r.transaction(async()=>{await r.member(teamId,user,['owner','admin','member']);const row=await this.find(teamId,id);if(input.expectedRevision!==row.revision)fail(409,'Workspace changed. Reload before saving.');const name=input.name??row.name;if(typeof name!=='string'||!name.trim()||name.length>100)fail(400,'Invalid workspace name');const canvas=input.canvas===undefined?row.canvas_json:JSON.stringify(input.canvas);if(input.canvas!==undefined&&!Array.isArray(input.canvas)||canvas.length>1000000)fail(400,'Invalid workspace canvas');await r.run('UPDATE shared_workspaces SET name=?,canvas_json=?,revision=revision+1 WHERE id=? AND revision=?',[name.trim(),canvas,id,row.revision]);await r.event(teamId,user,'workspace.updated',id);return r.get('SELECT * FROM shared_workspaces WHERE id=?',[id]);});}
 close(teamId,user,id,isOpen){const r=this.repository;return r.transaction(async()=>{await r.member(teamId,user);await this.find(teamId,id);if(typeof isOpen!=='boolean')fail(400,'isOpen must be boolean');await r.run('INSERT INTO shared_workspace_preferences(workspace_id,user_id,is_open) VALUES(?,?,?) ON CONFLICT(workspace_id,user_id) DO UPDATE SET is_open=excluded.is_open',[id,user,isOpen?1:0]);return{success:true};});}
 archive(teamId,user,id){const r=this.repository;return r.transaction(async()=>{await r.member(teamId,user,['owner','admin']);await this.find(teamId,id);await r.run('UPDATE shared_workspaces SET archived_at=CURRENT_TIMESTAMP,revision=revision+1 WHERE id=?',[id]);await r.event(teamId,user,'workspace.archived',id);return{success:true};});}
 resources(teamId,user,id){const r=this.repository;return r.transaction(async()=>{await r.member(teamId,user);await this.find(teamId,id);return r.all('SELECT a.* FROM team_assets a JOIN shared_workspace_resources w ON w.asset_id=a.id WHERE w.workspace_id=? AND a.team_id=?',[id,teamId]);});}
 attach(teamId,user,id,assetId){const r=this.repository;return r.transaction(async()=>{await r.member(teamId,user,['owner','admin','member']);await this.find(teamId,id);if(!await r.get('SELECT id FROM team_assets WHERE id=? AND team_id=?',[assetId,teamId]))fail(404,'Asset not found');await r.run('INSERT OR IGNORE INTO shared_workspace_resources(workspace_id,asset_id) VALUES(?,?)',[id,assetId]);return{success:true};});}
}
