import {frontendRoot,evidence,output} from './paths.mjs';
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),puppeteer=require('puppeteer');
const root=frontendRoot;
const {fixtureServer}=await import('./fixture-server.mjs');const server=await fixtureServer();
const port=server.httpServer.address().port;const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-first-run'],defaultViewport:{width:390,height:844,deviceScaleFactor:1,isMobile:true,hasTouch:true}});
const names=['Chat','Dashboard','Agents','AgentForge','Skills','Memory','Tools','ToolForge','WidgetManager','WidgetForge','Workflows','WorkflowForge','Goals','Traces','Artifacts','Connectors','Plugins','Marketplace','Settings','Autonomy','Experiments','Workspace'];const result=[];
try{for(const name of names){const page=await browser.newPage();const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,250));});await page.setRequestInterception(true);page.on('request',r=>{const u=r.url();if(u.startsWith('data:')||u.startsWith('blob:')||u.startsWith('http://127.0.0.1:'+port))r.continue();else{external.push(u);if(u.includes('pdf.min.js'))r.respond({status:200,contentType:'application/javascript',body:'window.pdfjsLib={GlobalWorkerOptions:{}};'});else r.respond({status:200,contentType:'text/css',body:''});}});
try{await page.goto(`http://127.0.0.1:${port}/_harness/mobile-all.html?screen=${name}Screen`,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(name=>!!window.MOBILE_FIXTURE?.getScreen()&&MOBILE_FIXTURE.screen.value!==false,{timeout:60000},name);await new Promise(r=>setTimeout(r,650));
for(const theme of ['dark','light']){await page.evaluate(theme=>{document.body.classList.remove('dark','light');document.body.classList.add(theme);},theme);for(const width of [320,390,800,1280]){await page.setViewport({width,height:900,isMobile:true,hasTouch:true});await new Promise(r=>setTimeout(r,130));const m=await page.evaluate(()=>{const root=document.querySelector('.cv-dashboard');const visible=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return e.getClientRects().length&&s.visibility!=='hidden'&&s.display!=='none'&&r.width>0&&r.height>0&&!e.closest('[inert]');};const scroller=e=>{for(let p=e.parentElement;p&&p!==root;p=p.parentElement){const s=getComputedStyle(p);if(['auto','scroll'].includes(s.overflowX)&&p.scrollWidth>p.clientWidth+2)return true;}return false;};const controls=[...root.querySelectorAll('input,textarea,select,button')].filter(visible);const escaped=controls.filter(e=>!scroller(e)).map(e=>{const r=e.getBoundingClientRect();return{label:e.textContent.trim().slice(0,45)||e.getAttribute('placeholder')||e.getAttribute('aria-label'),left:Math.round(r.left),right:Math.round(r.right)};}).filter(r=>r.left< -2||r.right>innerWidth+2);return {overflow:document.documentElement.scrollWidth-innerWidth,controls:controls.length,escaped:escaped.slice(0,12),text:root.innerText.slice(0,150)};});result.push({name,theme,width,...m});}
}await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await page.evaluate(()=>{document.body.classList.remove('light');document.body.classList.add('dark');});await page.screenshot({path:output(`ready-${name}.png`)});result.push({name,errors,externalBlocked:external.length});}catch(e){result.push({name,error:e.message,errors});}finally{await page.close();}console.log('DONE',name,result.filter(r=>r.name===name&&(r.error||r.overflow>0||r.escaped?.length||r.errors?.length)));}
fs.writeFileSync(output('bundled-matrix-release.json'),JSON.stringify(result,null,2),{flag:'wx'});const failures=result.filter(r=>r.error||r.errors?.length||r.overflow>0||r.width<=800&&r.escaped?.length);console.log(JSON.stringify({screens:names.length,layoutChecks:result.filter(r=>r.width).length,failures},null,2));if(failures.length)process.exitCode=1;
}finally{await browser.close();await server.close();}
