import {output} from './paths.mjs';
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {fixtureServer} from './fixture-server.mjs';const require=createRequire(import.meta.url),puppeteer=require('puppeteer');const server=await fixtureServer(),port=server.httpServer.address().port;const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-first-run','--js-flags=--max-old-space-size=512'],defaultViewport:{width:390,height:844,isMobile:true,hasTouch:true}});const results=[];
try{for(const name of ['Agents','Tools','Workflows','WidgetManager','Memory','Skills','Traces','Experiments','Goals','Settings','Connectors','Plugins','Marketplace','Artifacts']){const page=await browser.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.setRequestInterception(true);page.on('request',req=>{if(req.url().startsWith('http://127.0.0.1:'+port)||req.url().startsWith('data:')||req.url().startsWith('blob:'))req.continue();else if(req.url().includes('pdf.min.js'))req.respond({status:200,contentType:'text/javascript',body:'window.pdfjsLib={GlobalWorkerOptions:{}};'});else req.respond({status:200,contentType:'text/css',body:''});});try{await page.goto(`http://127.0.0.1:${port}/_harness/mobile-all.html?screen=${name}Screen`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!window.MOBILE_FIXTURE?.getScreen());await page.waitForFunction(()=>!!document.querySelector('.m-collection,.m-directory,.m-file-browser'));await new Promise(r=>setTimeout(r,160));await page.screenshot({path:output('reference-'+name+'.png')});const check=(label,pass,detail)=>checks.push({label,pass,...(detail?{detail}:{})});
const baseline=await page.evaluate(()=>{const el=document.querySelector('.m-directory,.m-collection,.m-file-browser'),r=el.getBoundingClientRect();return {visible:r.width>0&&r.height>100,width:r.width,records:el.querySelectorAll('.m-record').length,body:el.innerText.slice(0,700)};});check('Dedicated mobile layout is visible',baseline.visible,baseline);
if(name==='Artifacts'){await page.click('.m-file');await page.waitForFunction(()=>MOBILE_FIXTURE.getScreen().activeTab?.name==='briefing.md');await page.waitForSelector('.ce-preview-content',{visible:true});check('Selected file opens preview',await page.evaluate(()=>MOBILE_FIXTURE.getScreen().activeTab?.name==='briefing.md'));await page.click('.ce-mobile-modes [aria-label="Back to files"]');check('Back restores file browser',await page.$eval('.m-file-browser',e=>e.getBoundingClientRect().height>100));}
else if(['Settings','Connectors'].includes(name)){const item=name==='Settings'?'Sounds':'MCP';await page.evaluate(item=>[...document.querySelectorAll('.m-directory-item')].find(b=>b.innerText.includes(item)).click(),item);await page.waitForSelector('.mobile-section-back',{visible:true});check('Directory opens actual source subsection',await page.evaluate(name=>{const vm=MOBILE_FIXTURE.getScreen();return vm.activeSection===(name==='Settings'?'sounds':'mcp-servers')&&!vm.mobileDirectoryOpen;},name));await page.click('.mobile-section-back');check('Back restores directory',await page.$eval('.m-directory',e=>e.getBoundingClientRect().height>100));}
else if(baseline.records){const record=await page.$eval('.m-record',e=>e.dataset.recordId);await page.click('.m-record-open');await new Promise(r=>setTimeout(r,250));if(name==='Agents'){check('Agent selection survived click bubbling',await page.evaluate(()=>MOBILE_FIXTURE.getScreen().selectedAgent?.id==='agent-1'));check('Focused agent details shown',await page.$eval('.agent-details-section',e=>e.getBoundingClientRect().width>350));await page.evaluate(()=>[...document.querySelectorAll('.agent-details-section .tab-button')].find(b=>b.innerText.includes('Configure')).click());await page.waitForSelector('.agent-details-section textarea');check('Real system prompt retained',await page.$eval('.agent-details-section',e=>e.innerText.includes('System Prompt')&&e.innerText.includes('Tool Access')));check('Agent form matches mobile gutters',await page.$eval('.agent-details-section input[type=text]',e=>{const r=e.getBoundingClientRect();return r.left>=12&&r.right<=innerWidth-12&&r.width>=innerWidth-40;}));check('Compact identity header is present',await page.$eval('.m-agent-detail-header',e=>e.getBoundingClientRect().height>=44&&e.innerText.includes('Research assistant')));await page.screenshot({path:output('reference-AgentConfigure.png')});await page.click('.agent-details-section .close-button');check('Back returns same mobile list',await page.$eval('.m-collection',e=>getComputedStyle(e).display!=='none'));}
else if(name==='Goals')check('Existing goal detail opens',await page.$eval('.goal-detail-view',e=>e.getBoundingClientRect().width>350));else check('Existing inspector opens for selected record',await page.$eval('.right-panel-component',e=>e.classList.contains('mobile-panel-visible')));
if(name==='Goals'){await page.click('.goal-detail-back');}else if(name!=='Agents'){await page.evaluate(()=>document.querySelector('.right-panel-component .mobile-close-button')?.click());await new Promise(r=>setTimeout(r,70));}
const input=await page.$('.m-search input');if(input){await page.$eval('.m-search input',e=>{e.value='nothingmatches-fixture';e.dispatchEvent(new Event('input',{bubbles:true}));});await new Promise(r=>setTimeout(r,80));check('Search drives actual filtered records',await page.$$eval('.m-record',els=>els.length===0));}}
if(name==='Agents'){await page.$eval('.m-search input',e=>{e.value='';e.dispatchEvent(new Event('input',{bubbles:true}));});await new Promise(r=>setTimeout(r,50));await page.evaluate(()=>[...document.querySelectorAll('.m-tabs button')].find(b=>b.textContent.includes('Inactive')).click());await new Promise(r=>setTimeout(r,60));check('Status tab drives source filter',await page.evaluate(()=>MOBILE_FIXTURE.getScreen().agentTab==='inactive'&&MOBILE_FIXTURE.getScreen().filteredAgentsGrid.length===0));}
if(name==='WidgetManager'){await page.$eval('.m-search input',e=>{e.value='';e.dispatchEvent(new Event('input',{bubbles:true}));});await new Promise(r=>setTimeout(r,50));check('Widget action buttons retained',await page.evaluate(()=>['Edit','Duplicate','Export','Delete'].every(s=>[...document.querySelectorAll('.m-record-actions button')].some(b=>b.innerText===s))));}
const data={name,checks,errors};results.push(data);console.log(JSON.stringify(data));}catch(e){results.push({name,error:e.message,errors,checks});console.log(name,e.message);}finally{await page.close();}}
fs.writeFileSync(output('reference-journeys-complete.json'),JSON.stringify(results,null,2));const failed=results.filter(r=>r.error||r.errors.length||r.checks.some(c=>!c.pass));console.log('FAILURES',JSON.stringify(failed));if(failed.length)process.exitCode=1;}finally{await browser.close();await server.close();}
