import {describe,it,expect,vi} from 'vitest';
import {ResourceAuthorization} from './ResourceAuthorization.js';
function fixture(rows){const repository={get:vi.fn(async(sql,args)=>{const table=sql.match(/FROM "?(\w+)/)[1];return rows[table]?.[args[0]];})};const authorizeTeam=vi.fn(async()=>{});return {authorization:new ResourceAuthorization(repository,authorizeTeam),repository,authorizeTeam};}
describe('resource ownership decisions',()=>{
 it('authorizes legacy personal rows without requiring a migration first',async()=>{const {authorization}=fixture({agents:{a:{id:'a',created_by:'alice'}}});await expect(authorization.require({actorId:'alice'},'view','agents','a')).resolves.toMatchObject({scope:{kind:'personal'}});await expect(authorization.require({actorId:'bob'},'run','agents','a')).rejects.toMatchObject({status:404});});
 it('inherits ownership for versions rather than treating their author as owner',async()=>{const {authorization}=fixture({workflow_versions:{v:{id:'v',workflow_id:'w',created_by:'bob'}},workflows:{w:{id:'w',user_id:'alice'}}});await expect(authorization.require({actorId:'alice'},'view','workflow_versions','v')).resolves.toBeTruthy();await expect(authorization.require({actorId:'bob'},'view','workflow_versions','v')).rejects.toMatchObject({status:404});});
 it('checks live team authority even when the caller created the resource',async()=>{const {authorization,authorizeTeam}=fixture({agents:{a:{id:'a',created_by:'alice',scope_id:'w'}},ownership_scopes:{w:{id:'w',kind:'workspace',team_id:'t'}}});authorizeTeam.mockRejectedValue(Object.assign(Error('Removed'),{status:403}));await expect(authorization.require({actorId:'alice'},'run','agents','a')).rejects.toMatchObject({status:403});expect(authorizeTeam).toHaveBeenCalledWith({actorId:'alice'},'run',{id:'w',kind:'workspace',team_id:'t'});});
 it('does not fall back to personal ownership if a scope is missing',async()=>{const {authorization}=fixture({agents:{a:{id:'a',created_by:'alice',scope_id:'missing'}}});await expect(authorization.require({actorId:'alice'},'edit','agents','a')).rejects.toMatchObject({status:403});});
 it('refuses unclassified resource names, system tables, unauthenticated actors and unknown actions',async()=>{const {authorization,repository}=fixture({});for(const table of ['users','unclassified','agents;DROP TABLE agents'])await expect(authorization.require({actorId:'alice'},'view',table,'a')).rejects.toMatchObject({status:403});await expect(authorization.require({},'view','agents','a')).rejects.toMatchObject({status:401});await expect(authorization.require({actorId:'alice'},'impersonate','agents','a')).rejects.toMatchObject({status:403});expect(repository.get).not.toHaveBeenCalled();});
});
