import express from 'express';

import TaskModel from '../models/TaskModel.js';
import GoalModel from '../models/GoalModel.js';
import TaskOrchestrator from '../services/goal/TaskOrchestrator.js';
import { recordLlmCall } from '../services/execution/LedgerRecorder.js';
import { mintNodeToken, presentedToken, verifyNodeToken } from '../services/cluster/clusterToken.js';
import { checkSpendAdmission } from '../services/cluster/admission.js';
import { listNodes, touchNode } from '../services/cluster/nodeRegistry.js';
import { describeNode } from '../services/cluster/nodeIdentity.js';
import { authenticateToken } from './Middleware.js';

/**
 * The wire between a primary and its worker nodes.
 *
 * ---------------------------------------------------------------------------
 * WHY THE PRIMARY KEEPS THE DATABASE
 * ---------------------------------------------------------------------------
 * The obvious multi-node design is a shared database. It is also a multi-week
 * rewrite here: this backend is sqlite3 callback-style end to end across fifty
 * model files, with json_each and this.changes throughout, and none of that
 * survives a port to a network database.
 *
 * So the primary IS the ledger, and workers reach it over HTTP. One writer,
 * one file, no network sqlite — which means the WAL "multiple containers can
 * safely access the same database" note in docker-compose.yml never becomes
 * load-bearing, because the file is never shared. It also means realtimeSync
 * needs no Redis adapter: every socket still belongs to the primary.
 *
 * ---------------------------------------------------------------------------
 * TWO CREDENTIALS, TWO AUDIENCES
 * ---------------------------------------------------------------------------
 * /enroll and /nodes are OPERATOR routes: a signed-in human, `authenticateToken`.
 * Everything else is a NODE route: a machine holding a grant this primary
 * minted, `authenticateClusterNode`.
 *
 * They must not be interchangeable in either direction. A user session token
 * cannot claim work (it lacks the cluster audience) and a node grant cannot
 * reach the rest of the API (it is signed with a different secret entirely).
 * See services/cluster/clusterToken.js.
 */

const ClusterRoutes = express.Router();

/**
 * Node authentication.
 *
 * Named for routeSecurity.test.js: it is a real guard because it REJECTS —
 * the property that test cares about — and it is registered in that file's
 * GUARD_NAMES alongside authenticateGateway, which is the same situation (a
 * credential scheme of its own, opening exactly one router and nothing else).
 */
function authenticateClusterNode(req, res, next) {
  const grant = verifyNodeToken(presentedToken(req));
  if (!grant) {
    return res.status(401).json({
      error: 'Invalid or expired cluster node grant.',
      code: 'cluster_grant_invalid',
    });
  }
  // Identity comes from the TOKEN, never from the body. If a worker named
  // itself in the payload, any node could renew or release another node's
  // claims simply by naming it.
  req.clusterNode = grant;
  return next();
}

/**
 * POST /api/cluster/enroll — operator mints a grant for a new worker.
 *
 * The node id is generated by the primary and embedded in the token. The
 * operator copies the token into the worker's environment; the worker never
 * chooses who it is.
 */
ClusterRoutes.post('/enroll', authenticateToken, (req, res) => {
  try {
    const { label = '', ttlDays } = req.body || {};
    const grant = mintNodeToken({ userId: req.user.userId, label, ...(ttlDays ? { ttlDays } : {}) });
    // The token is returned exactly once and never stored here: this primary
    // can always mint another, and keeping a copy would turn a list of node
    // names into a list of live credentials.
    res.json({
      success: true,
      nodeId: grant.nodeId,
      token: grant.token,
      expiresAt: grant.expiresAt,
      env: {
        AGNT_NODE_ROLE: 'worker',
        AGNT_CLUSTER_PRIMARY: `${req.protocol}://${req.get('host')}`,
        AGNT_CLUSTER_TOKEN: grant.token,
      },
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

/** GET /api/cluster/nodes — operator's fleet view. */
ClusterRoutes.get('/nodes', authenticateToken, (req, res) => {
  res.json({
    success: true,
    self: describeNode(),
    nodes: listNodes(req.user.userId),
  });
});

/** GET /api/cluster/whoami — lets a worker prove its grant works before polling. */
ClusterRoutes.get('/whoami', authenticateClusterNode, (req, res) => {
  touchNode(req.clusterNode, 'ping');
  res.json({ success: true, nodeId: req.clusterNode.nodeId, label: req.clusterNode.label });
});

/**
 * POST /api/cluster/claim — hand out at most one task.
 *
 * 204 (not 404, not an empty 200 with a null body) when there is nothing to
 * do: "no content" is exactly what happened, and it keeps the worker's polling
 * loop from having to distinguish an empty queue from an error.
 */
ClusterRoutes.post('/claim', authenticateClusterNode, async (req, res) => {
  try {
    const { nodeId, userId } = req.clusterNode;
    const { goalId = null, leaseMs } = req.body || {};

    // Liveness is recorded BEFORE anything can return, because for a healthy
    // worker the poll IS the heartbeat — asking for work is the only thing it
    // does when there is none. Recording it after the empty-queue 204 meant a
    // worker that had nothing to do never appeared in the fleet view at all,
    // and one that went idle after working slowly aged into `stale: true`. The
    // operator then cannot tell "alive, queue is empty" from "dead", and gets
    // the wrong answer precisely when the queue is quiet, which is most of the
    // time. A budget refusal below is also a live node, so this sits above
    // that too. 'poll' touches lastSeen only — `claims` still counts claims.
    touchNode(req.clusterNode, 'poll');

    // The claim IS the meter. Refusing here stops NEW work while every task
    // already in flight runs to completion — which is the only humane place to
    // enforce a budget.
    const admission = await checkSpendAdmission(userId);
    if (!admission.admit) {
      // 429, not 402 or 403: this is "not now", and a worker that backs off
      // and retries is exactly the correct behaviour. A 4xx implying a
      // permanent refusal would make workers give up on a ceiling that resets
      // at midnight.
      return res.status(429).json({
        error: 'Spend ceiling reached — no new work is being admitted.',
        code: admission.reason,
        spentUsd: admission.spentUsd,
        hardLimitUsd: admission.hardLimitUsd,
      });
    }

    const task = await TaskModel.claimNext(nodeId, {
      userId, // scoping lives in SQL — see TaskModel.claimNext
      goalId,
      ...(leaseMs ? { leaseMs } : {}),
    });

    if (!task) return res.status(204).end();

    touchNode(req.clusterNode, 'claim');

    // Goal context travels with the task. A worker holds no goal state of its
    // own, and a task title alone is not enough for an agent to do the work.
    const goal = await GoalModel.findOne(task.goal_id).catch(() => null);

    res.json({
      success: true,
      task: {
        id: task.id,
        goalId: task.goal_id,
        title: task.title,
        description: task.description,
        requiredTools: task.required_tools || [],
        agentName: task.agent_name || null,
        input: task.input || null,
        orderIndex: task.order_index,
      },
      goal: goal ? { id: goal.id, title: goal.title, description: goal.description } : null,
      leaseMs: leaseMs || TaskModel.DEFAULT_LEASE_MS,
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

/** POST /api/cluster/renew — extend a lease this node holds. */
ClusterRoutes.post('/renew', authenticateClusterNode, async (req, res) => {
  try {
    const { taskId, leaseMs } = req.body || {};
    if (!taskId) return res.status(400).json({ error: 'taskId is required' });

    const renewed = await TaskModel.renewClaim(taskId, req.clusterNode.nodeId, leaseMs || undefined);
    touchNode(req.clusterNode, 'ping');

    // 409, not 401: the grant is fine, the CLAIM is gone. A worker that reads
    // this as an auth failure would re-enrol instead of stopping work it no
    // longer owns.
    if (!renewed) return res.status(409).json({ error: 'Claim lost', code: 'claim_lost' });
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

/** POST /api/cluster/release — give a claim back without waiting out the lease. */
ClusterRoutes.post('/release', authenticateClusterNode, async (req, res) => {
  try {
    const { taskId } = req.body || {};
    if (!taskId) return res.status(400).json({ error: 'taskId is required' });

    await TaskModel.releaseClaim(taskId, req.clusterNode.nodeId);
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

/**
 * POST /api/cluster/complete — report the outcome of a claimed task.
 *
 * The success path deliberately routes through TaskOrchestrator.processTaskResult,
 * the same function the local path uses, rather than writing `output` directly.
 * Two writers producing two shapes for one column is how a downstream reader
 * ends up with a special case per execution site — and the goal evaluator,
 * which reads these outputs, must not have to know where the work ran.
 */
ClusterRoutes.post('/complete', authenticateClusterNode, async (req, res) => {
  try {
    const { taskId, status = 'completed', result = null, error = null, spend = [] } = req.body || {};
    if (!taskId) return res.status(400).json({ error: 'taskId is required' });

    // Read the owning goal before the row is mutated, so the completion check
    // below has it regardless of what happens to the claim.
    const taskRow = await TaskModel.findOne(taskId).catch(() => null);

    // Ownership is re-checked at the write, not assumed from the claim: a
    // lease can lapse WHILE the work runs, and another node may already have
    // taken over. Accepting this write anyway would let a slow node overwrite
    // a fresher result.
    const stillOurs = await TaskModel.renewClaim(taskId, req.clusterNode.nodeId);
    if (!stillOurs) {
      return res.status(409).json({ error: 'Claim lost — result rejected', code: 'claim_lost' });
    }

    if (status === 'completed') {
      await TaskOrchestrator.processTaskResult(taskId, result || {});
      touchNode(req.clusterNode, 'complete');
    } else {
      await TaskModel.updateStatus(taskId, 'failed', null, null, null, null, null, error || 'Worker reported failure');
      touchNode(req.clusterNode, 'fail');
    }

    await recordWorkerSpend(req.clusterNode, taskId, spend);

    await TaskModel.releaseClaim(taskId, req.clusterNode.nodeId);
    res.json({ success: true });

    // Deliberately AFTER the response and deliberately not awaited: finishing
    // a goal runs an evaluation, which is an LLM call. Holding a worker's poll
    // loop open for the length of somebody else's evaluation would idle the
    // whole fleet behind one node's bookkeeping.
    completeGoalIfFinished(taskRow?.goal_id);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * A goal finished by the FLEET has to finish the same way one finished locally
 * does.
 *
 * The primary's dispatch loop checks for completion when it runs the last task
 * itself, but it walks each order_index group exactly once and returns. When
 * the last task is finished by a WORKER — minutes later, in another process —
 * that loop is long gone, so nothing downstream would ever notice. The goal
 * would sit in 'executing' forever with every one of its tasks complete: no
 * evaluation, no auto-merge back to the conversation, no insight extraction.
 *
 * That gap is invisible until work actually leaves the primary, which is
 * exactly what bounding the primary's own dispatch now makes routine.
 *
 * Never allowed to fail anything. The task result is already durably recorded
 * by the time this runs; a bookkeeping error here must not be reported to the
 * worker as a rejected result.
 */
async function completeGoalIfFinished(goalId) {
  if (!goalId) return;
  try {
    // The autonomous loop owns its own completion — same carve-out the local
    // path makes. Completing the goal underneath it would end the loop early.
    if (TaskOrchestrator.runningGoals?.get(goalId)?.autonomous) return;
    if (!(await TaskOrchestrator.checkGoalCompletion(goalId))) return;
    await TaskOrchestrator.completeGoal(goalId);
  } catch (err) {
    console.error(`[cluster] goal ${goalId} finished but could not be completed: ${err.message}`);
  }
}

/**
 * Copy a worker's measured spend into the primary's ledger.
 *
 * WHY THE PRIMARY RECORDS SPEND IT DID NOT INCUR
 * ─────────────────────────────────────────────
 * A worker calls providers with its OWN credentials and writes its own ledger
 * rows — into its own database, which the operator never looks at. Without
 * this, fleet spend would be scattered across N sqlite files and the answer to
 * "what is this costing me" would require logging into every node.
 *
 * The rows carry the WORKER's node id, not ours. Stamping the primary here
 * would produce a per-node breakdown that is uniform, plausible and wrong —
 * which is worse than not having one.
 *
 * Never throws. A bookkeeping failure must not turn a completed task into a
 * failed one; that is the same rule LedgerRecorder itself lives by.
 */
async function recordWorkerSpend(node, taskId, spend) {
  if (!Array.isArray(spend) || spend.length === 0) return;
  for (const row of spend.slice(0, 200)) {
    try {
      await recordLlmCall({
        userId: node.userId,
        origin: 'goal_task',
        originId: row.originId || null,
        provider: row.provider,
        model: row.model,
        // Tokens travel, prices do not: the primary re-prices from its own
        // catalogue so every figure in one ledger was produced by one pricing
        // table. A worker with a stale catalogue cannot skew the total.
        usage: {
          inputTokens: row.input_tokens,
          outputTokens: row.output_tokens,
          cacheReadTokens: row.cache_read_tokens,
          cacheCreation5mTokens: row.cache_write_5m_tokens,
          cacheCreation1hTokens: row.cache_write_1h_tokens,
        },
        durationMs: row.duration_ms ?? null,
        status: row.status || 'ok',
        error: row.error || null,
        nodeId: node.nodeId,
      });
    } catch (error) {
      console.warn(`[cluster] could not record worker spend for task ${taskId}: ${error.message}`);
    }
  }
}

export default ClusterRoutes;
