import {describe,it,expect,vi} from 'vitest';
import express from 'express';
import {createServer} from 'node:http';
import {once} from 'node:events';
vi.mock('../utils/authGuard.js',()=>({requireAuthHeader:(req,res,next)=>{if(req.headers.authorization!=='Bearer fixture')return res.status(401).end();next();}}));
import {createCodexVoiceRouter} from './codexVoiceRoutes.js';
import {CodexVoiceError} from '../services/codexRealtimeVoiceService.js';
const SDP='v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\n';
async function withServer(deps,run){const app=express();app.use('/api/speech/codex',createCodexVoiceRouter(deps));const server=createServer(app);server.listen(0,'127.0.0.1');await once(server,'listening');try{await run(`http://127.0.0.1:${server.address().port}/api/speech/codex`);}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}}
const headers={Authorization:'Bearer fixture','Content-Type':'application/sdp'};
describe('Codex voice HTTP contract (fixture auth and provider)',()=>{
 it('refuses unauthenticated setup before provider execution',async()=>{const createCall=vi.fn();await withServer({createCall},async base=>{expect((await fetch(base+'/call',{method:'POST',body:SDP})).status).toBe(401);});expect(createCall).not.toHaveBeenCalled();});
 it('returns SDP and exact selected provider without forwarding arbitrary query fields',async()=>{const createCall=vi.fn(async()=>({sdp:SDP}));await withServer({createCall},async base=>{const response=await fetch(base+'/call?provider=openai-codex-2&voice=cove&url=https://evil.invalid&token=ignored',{method:'POST',headers,body:SDP});expect(response.status).toBe(200);expect(response.headers.get('content-type')).toContain('application/sdp');expect(await response.text()).toBe(SDP);});expect(createCall).toHaveBeenCalledTimes(1);expect(Object.keys(createCall.mock.calls[0][0]).sort()).toEqual(['provider','sdp','signal','voice']);expect(createCall.mock.calls[0][0].provider).toBe('openai-codex-2');});
 it('retains typed quota error',async()=>await withServer({createCall:async()=>{throw new CodexVoiceError('voice_rate_limited',429);}},async base=>{const response=await fetch(base+'/call',{method:'POST',headers,body:SDP});expect(response.status).toBe(429);expect(await response.json()).toEqual({success:false,code:'voice_rate_limited'});}));
 it('sanitizes unknown errors',async()=>await withServer({createCall:async()=>{throw new Error('private upstream details');}},async base=>{const response=await fetch(base+'/call',{method:'POST',headers,body:SDP});expect(await response.text()).not.toContain('private');expect(response.status).toBe(502);}));
 it('catalog returns unverified registration only',async()=>{const status=vi.fn(async provider=>({provider,registered:true,entitlement:'unverified'}));await withServer({status},async base=>{const response=await fetch(base+'/capabilities?provider=openai-codex',{headers});expect(await response.json()).toEqual({success:true,provider:'openai-codex',registered:true,entitlement:'unverified'});});expect(status).toHaveBeenCalledExactlyOnceWith('openai-codex');});
 it('body parser refuses excessive SDP before dispatch',async()=>{const createCall=vi.fn();await withServer({createCall},async base=>{const response=await fetch(base+'/call',{method:'POST',headers,body:'x'.repeat(270000)});expect(response.status).toBe(413);});expect(createCall).not.toHaveBeenCalled();});
 it('client disconnect aborts provider signal',async()=>{let resolveStart,resolveAbort;const started=new Promise(r=>resolveStart=r);const aborted=new Promise(r=>resolveAbort=r);const createCall=async({signal})=>{resolveStart();await new Promise(resolve=>signal.addEventListener('abort',()=>{resolveAbort();resolve();},{once:true}));throw new CodexVoiceError('voice_setup_cancelled',499);};await withServer({createCall},async base=>{const c=new AbortController();const pending=fetch(base+'/call',{method:'POST',headers,body:SDP,signal:c.signal}).catch(()=>{});await started;c.abort();await Promise.race([aborted,new Promise((_,reject)=>setTimeout(()=>reject(new Error('abort_not_observed')),1000))]);await pending;});});
});
