import {describe,it,expect,beforeAll,afterAll,vi} from 'vitest';
import express from 'express';import http from 'node:http';import sqlite3 from 'sqlite3';
import {initializeLearningSchema} from '../models/database/learningSchema.js';
import {LearningCoordinator} from '../services/learning/LearningCoordinator.js';
vi.mock('./Middleware.js',()=>({authenticateToken:(req,res,next)=>{if(!req.headers['x-test-user'])return res.status(401).json({error:'account_required'});req.user={userId:req.headers['x-test-user']};next();}}));
let db,service,server,base,finding;
beforeAll(async()=>{db=await new Promise((resolve,reject)=>{const c=new sqlite3.Database(':memory:',e=>e?reject(e):resolve(c));});await initializeLearningSchema(db);service=new LearningCoordinator(db);for(let i=0;i<25;i++){const w=await service.work('owner','agent','run-'+i);await service.append('owner',w.id,{eventKey:'e-'+i,type:'tool_outcome',capability:'read_file',outcome:i<5?'failed':'succeeded',errorKind:i<5?'timeout':null,occurredAt:Date.now()-1000});}finding=(await service.summary('owner')).findings[0];const {createLearningRoutes}=await import('./LearningRoutes.js');const app=express();app.use(express.json());app.use('/learning',createLearningRoutes(async()=>service));server=http.createServer(app);await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;});
afterAll(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await new Promise(r=>db.close(r));});
const call=async(path,user,body)=>{const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(user?{'x-test-user':user}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};};
describe('real account-scoped learning API',()=>{
 it('requires an authenticated account and never returns another account evidence',async()=>{expect((await call('/learning')).status).toBe(401);expect((await call('/learning','other')).body.findings).toEqual([]);expect((await call('/learning/events','other')).body.events).toEqual([]);});
 it('blocks cross-account actions before exposing object details',async()=>{const r=await call('/learning/findings/'+finding.id+'/approve','other',{revision:finding.revision,candidateHash:finding.candidate_hash});expect(r.status).toBe(404);expect(r.body.error).toBe('not_found');});
 it('runs owner approval with hash binding and rejects arbitrary payloads',async()=>{expect((await call('/learning/findings/'+finding.id+'/approve','owner',{revision:finding.revision,candidateHash:finding.candidate_hash,action:'send_email'})).status).toBe(400);const r=await call('/learning/findings/'+finding.id+'/approve','owner',{revision:finding.revision,candidateHash:finding.candidate_hash});expect(r.status).toBe(200);expect(r.body.trial.state).toBe('watching');expect((await call('/learning/trials/'+r.body.trial.id+'/undo','other',{revision:1})).status).toBe(404);expect((await call('/learning/trials/'+r.body.trial.id+'/undo','owner',{revision:1})).body.restored).toBe(true);});
});
