import {it,expect,vi,afterEach} from 'vitest';import express from 'express';
import db,{dbReady} from '../models/database/index.js';import {databaseRepository} from '../services/authorization/ScopeRepository.js';import {migrateOwnership} from '../services/authorization/OwnershipMigration.js';import {installOwnershipTriggers} from '../services/authorization/OwnershipTriggers.js';import {OWNERSHIP_INVENTORY} from '../services/authorization/OwnershipInventory.js';import {createScopeApiMiddleware} from './ScopeApiMiddleware.js';import {trustedScopeRequest} from '../services/authorization/ScopeRequestContext.js';
vi.mock('../services/CloudTeamClient.js',()=>({CloudTeamClient:class{async access(token,teamId){if(token==='Bearer removed')throw Object.assign(Error('Removed'),{status:403});return {id:teamId,role:token==='Bearer viewer'?'viewer':'member'};}}}));
afterEach(()=>vi.unstubAllEnvs());
it('native API lists, creates and updates share the scope owner, never a teammate or another workspace',async()=>{
 await dbReady;const r=databaseRepository(db);await migrateOwnership(r);await installOwnershipTriggers(r,OWNERSHIP_INVENTORY);vi.stubEnv('AGNT_TENANT_SLUG','example');
 const auth=(req,res,next)=>{req.user={id:'alice',userId:'alice'};next();};const app=express();app.use(express.json());app.use('/api',createScopeApiMiddleware(auth,async id=>({id,team_id:'team'})));
 app.post('/api/goals/create',async(req,res)=>{await r.run('INSERT INTO goals(id,user_id,title,description) VALUES(?,?,?,?)',[req.body.id,req.user.id,req.body.title,'Description']);res.json({owner:req.user.id,actor:trustedScopeRequest(req).actorId});});
 app.get('/api/goals',async(req,res)=>res.json(await r.all('SELECT id,title,scope_id FROM goals WHERE user_id=?',[req.user.id])));
 app.get('/api/goals/:id',async(req,res)=>res.json(await r.get('SELECT * FROM goals WHERE id=?',[req.params.id])));
 const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
 const call=async(path,workspace='one',method='GET',body,token='member')=>{const response=await fetch(`http://127.0.0.1:${server.address().port}/api${path}`,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,'X-AGNT-Team-ID':'team','X-AGNT-Workspace-ID':workspace},...(body?{body:JSON.stringify(body)}:{})});return{status:response.status,body:await response.json()};};
 try{const created=await call('/goals/create','one','POST',{id:'shared-goal',title:'Shared'});expect(created.status).toBe(200);expect(created.body.owner).toMatch(/^scope:/);expect(created.body.actor).toBe('alice');expect((await call('/goals')).body).toHaveLength(1);expect((await call('/goals','two')).body).toEqual([]);expect((await call('/goals/shared-goal','two')).status).toBe(404);expect((await call('/goals/create','one','POST',{id:'denied',title:'Denied'},'viewer')).status).toBe(403);expect((await call('/goals','one','GET',null,'removed')).status).toBe(403);expect((await call('/plugins')).status).toBe(403);}finally{await new Promise(resolve=>server.close(resolve));}
},30000);
