import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { flushPromises, mount } from '@vue/test-utils';
import { createStore } from 'vuex';
import CanvasScreen from './CanvasScreen.vue';
import WorkspaceSwitcher from './WorkspaceSwitcher.vue';
import TeamWorkspace from '@/views/_components/one/TeamWorkspace.vue';
import { NAVIGATION_CHANGED_EVENT, updateNavigationItem } from '@/services/navigationPreferences.js';
const mounted=[];
const teams=[{id:'engineering',name:'Engineering',role:'owner'},{id:'research',name:'Research',role:'member'}];
beforeEach(()=>{vi.stubGlobal('ResizeObserver',class{observe(){} disconnect(){}});localStorage.clear();vi.stubGlobal('fetch',vi.fn(async()=>({ok:true,json:async()=>teams})));});
afterEach(()=>{mounted.splice(0).forEach(w=>w.unmount());vi.unstubAllGlobals();document.body.innerHTML='';});
function setup(){const pages=[{id:'chat',name:'Chat',route:'ChatScreen'},{id:'goal',name:'Goals',route:'GoalsScreen'},{id:'custom',name:'Scratch',route:'custom:scratch'}];const store=createStore({modules:{
 userAuth:{namespaced:true,state:()=>({token:'user-1'}),getters:{isAuthenticated:()=>true}},
 aiProvider:{namespaced:true,state:()=>({selectedProvider:'openai',selectedModel:'gpt-4o'})},
 widgetLayout:{namespaced:true,state:()=>({pages}),getters:{allPages:s=>s.pages,activePageId:()=> 'custom',activePage:()=>pages[2],isLoaded:()=>true,pageForRoute:s=>route=>s.pages.find(p=>p.route===route)},actions:{setActivePage:vi.fn(),createPageFromDefault:vi.fn(),fetchLayouts:vi.fn()}},
 shell:{namespaced:true,state:()=>({jump:false}),getters:{jumpOpen:s=>s.jump,inspect:()=>null,updateAvailable:()=>false},mutations:{open(s){s.jump=true}},actions:{openJump({commit}){commit('open')},toggleJump({commit}){commit('open')}}}},
 getters:{'contentOutputs/unreadOutputIdSet':()=>new Set(['unread']),'chat/streamingOutputIds':()=>new Set()},
});const wrapper=mount(CanvasScreen,{attachTo:document.body,props:{screenName:'ChatScreen'},slots:{default:'<input id="personal-draft" value="keep my draft" />'},global:{plugins:[store],directives:{tooltip:{}},stubs:{Tooltip:{template:'<div class="tooltip-container"><slot /></div>'},WidgetCanvas:true,WidgetCatalog:true,ChatProviderSelector:true,SimpleModal:true,PanelBackdrop:true,JumpPalette:true,TeamWorkspace:{name:'TeamWorkspace',props:['selectedTeamId','initialTab','hideScopeSelector'],emits:['close','update:selectedTeamId','teams-loaded'],template:'<section class="team-fixture">{{selectedTeamId}} {{initialTab}}</section>'}}}});mounted.push(wrapper);return{wrapper,store};}
describe('reference sidebar ordering and context',()=>{
 // The rail renders the Settings → Navigation registry verbatim. Search is the
 // only hardcoded row above it, because it opens the palette instead of going
 // anywhere. Nothing is filtered out: the rail used to drop chat, goals and
 // artifacts — the exact three that ship visible — so its configurable half
 // rendered nothing and Settings described a sidebar nobody had.
 it('renders the settings registry verbatim, after the workspace selector and Search',async()=>{const{wrapper}=setup();await flushPromises();const rail=wrapper.find('.cv-sidebar');expect(rail.element.firstElementChild.classList.contains('workspace-switcher')).toBe(true);expect(wrapper.findAll('[data-primary]').map(b=>b.attributes('aria-label'))).toEqual(['Search']);expect(wrapper.findAll('.cv-sb-pages .cv-sb-page').map(b=>b.attributes('aria-label'))).toEqual(['Chat','Goals','Files','Library','Teams','Scratch']);expect(wrapper.findAll('.cv-sb-pages .cv-sb-cap-text').map(c=>c.text())).toEqual(['TODAY','WORK','ASSETS','PERSONAL']);expect(wrapper.findComponent(WorkspaceSwitcher).props('modelValue')).toBe('');expect(rail.text()).toContain('Personal');expect(wrapper.findAll('.cv-sb-pages [data-tour-id="sidebar.chat"]')).toHaveLength(1);expect(wrapper.findAll('.cv-sb-pages [data-tour-id="sidebar.goals"]')).toHaveLength(1);});
 it('follows Settings when a row is hidden, regrouped or reordered',async()=>{const{wrapper}=setup();await flushPromises();updateNavigationItem('section:goals',{visible:false});updateNavigationItem('virtual:teams',{group:'Focus'});updateNavigationItem('section:store',{visible:true});window.dispatchEvent(new CustomEvent(NAVIGATION_CHANGED_EVENT));await flushPromises();expect(wrapper.findAll('.cv-sb-pages .cv-sb-page').map(b=>b.attributes('aria-label'))).toEqual(['Chat','Files','Library','Store','Scratch','Teams']);expect(wrapper.findAll('.cv-sb-pages .cv-sb-cap-text').map(c=>c.text())).toEqual(['TODAY','WORK','ASSETS','CONNECTORS','PERSONAL','FOCUS']);});
 it('opens real destinations and preserves mounted personal draft under Library',async()=>{const{wrapper,store}=setup();await flushPromises();const draft=wrapper.find('#personal-draft').element;await wrapper.find('[data-tour-id="sidebar.library"]').trigger('click');expect(wrapper.findComponent({name:'LibraryHome'}).exists()).toBe(true);expect(wrapper.find('#personal-draft').element).toBe(draft);expect(wrapper.find('[data-tour-id="sidebar.library"]').attributes('aria-current')).toBe('page');expect(wrapper.find('.cv-sb-pages [data-tour-id="sidebar.chat"]').attributes('aria-current')).toBeUndefined();expect(wrapper.find('panel-backdrop-stub').exists()).toBe(false);await wrapper.find('.cv-sb-pages [data-tour-id="sidebar.goals"]').trigger('click');expect(wrapper.emitted('screen-change').at(-1)[0]).toBe('GoalsScreen');expect(wrapper.findComponent({name:'LibraryHome'}).exists()).toBe(false);await wrapper.find('.cv-sb-pages [data-tour-id="sidebar.chat"]').trigger('click');expect(wrapper.emitted('screen-change').at(-1)[0]).toBe('ChatScreen');expect(wrapper.find('.cv-sb-pages [data-tour-id="sidebar.chat"]').attributes('aria-current')).toBe('page');await wrapper.find('[data-primary="find"]').trigger('click');expect(store.getters['shell/jumpOpen']).toBe(true)});
 it('selects a team by actual ID, synchronizes its panel, and does not mislabel personal chat as shared',async()=>{const{wrapper}=setup();await flushPromises();const picker=wrapper.findComponent(WorkspaceSwitcher);picker.vm.$emit('select','engineering');await flushPromises();expect(picker.props('modelValue')).toBe('engineering');expect(wrapper.findComponent({name:'TeamWorkspace'}).props()).toMatchObject({selectedTeamId:'engineering',initialTab:'Assets',hideScopeSelector:true});expect(wrapper.find('[data-tour-id="sidebar.library"]').attributes('aria-current')).toBe('page');await wrapper.find('[data-tour-id="sidebar.teams"]').trigger('click');expect(wrapper.findComponent({name:'TeamWorkspace'}).props('initialTab')).toBe('Members');expect(wrapper.find('[data-tour-id="sidebar.teams"]').attributes('aria-current')).toBe('page');wrapper.findComponent({name:'TeamWorkspace'}).vm.$emit('update:selectedTeamId','research');await flushPromises();expect(picker.props('modelValue')).toBe('research');await wrapper.find('.cv-sb-pages [data-tour-id="sidebar.chat"]').trigger('click');expect(picker.props('modelValue')).toBe('');expect(wrapper.find('#personal-draft').element.value).toBe('keep my draft');});
 it('updates newly created team labels without fake sample workspaces',async()=>{const{wrapper}=setup();await flushPromises();await wrapper.find('[data-tour-id="sidebar.teams"]').trigger('click');const panel=wrapper.findComponent({name:'TeamWorkspace'});panel.vm.$emit('teams-loaded',[...teams,{id:'design',name:'Design',role:'owner'}]);panel.vm.$emit('update:selectedTeamId','design');await flushPromises();expect(wrapper.findComponent(WorkspaceSwitcher).text()).toContain('Design');});
 it('clears selected team on identity change',async()=>{const{wrapper,store}=setup();await flushPromises();wrapper.findComponent(WorkspaceSwitcher).vm.$emit('select','engineering');await flushPromises();store.state.userAuth.token='user-2';await flushPromises();expect(wrapper.findComponent(WorkspaceSwitcher).props('modelValue')).toBe('');expect(wrapper.find('.team-fixture').exists()).toBe(false)});
 it('keeps custom pages on the rail without turning them into sections',async()=>{const{wrapper}=setup();await flushPromises();const scratch=wrapper.findAll('.cv-sb-pages button').find(b=>b.text().includes('Scratch'));expect(scratch).toBeTruthy();expect(scratch.attributes('data-tour-id')).toBeUndefined();await scratch.trigger('click');expect(wrapper.find('widget-canvas-stub').exists()).toBe(true);await wrapper.find('[data-tour-id="sidebar.library"]').trigger('click');expect(wrapper.find('.library-home').isVisible()).toBe(true);});
 it('shows team-load failure without claiming a team is selected',async()=>{global.fetch.mockResolvedValue({ok:false,status:503});const{wrapper}=setup();await flushPromises();expect(wrapper.findComponent(WorkspaceSwitcher).props('error')).toContain('Cannot load');expect(wrapper.findComponent(WorkspaceSwitcher).props('modelValue')).toBe('')});
});
describe('controlled team panel selection',()=>{
 it('loads shell selection and emits changes from team selection',async()=>{global.fetch.mockImplementation(async url=>({ok:true,json:async()=>url.endsWith('/teams')?teams:[]}));const store=createStore({state:{userAuth:{token:'t'}},getters:{'agents/allAgents':()=>[],'workflows/allWorkflows':()=>[],'skills/allSkills':()=>[]}});const wrapper=mount(TeamWorkspace,{props:{selectedTeamId:'engineering',initialTab:'Members',hideScopeSelector:true},global:{plugins:[store],directives:{tooltip:{}}}});mounted.push(wrapper);await flushPromises();expect(wrapper.find('header [role="combobox"]').exists()).toBe(false);expect(wrapper.find('nav .active').text()).toBe('Members');expect(wrapper.emitted('teams-loaded')[0][0]).toEqual(teams);expect(global.fetch.mock.calls.some(([url])=>url.includes('/engineering/members'))).toBe(true);await wrapper.setProps({selectedTeamId:'research',initialTab:'Assets'});await flushPromises();expect(global.fetch.mock.calls.some(([url])=>url.includes('/research/assets'))).toBe(true);expect(wrapper.find('nav .active').text()).toBe('Assets');expect(wrapper.emitted('update:selectedTeamId').at(-1)).toEqual(['research']);});
});
