import { afterEach, describe, expect, it } from 'vitest';
import { mount, flushPromises } from '@vue/test-utils';
import WorkspaceSwitcher from './WorkspaceSwitcher.vue';
const wrappers=[];
afterEach(()=>{wrappers.splice(0).forEach(w=>w.unmount());document.body.innerHTML='';});
function setup(props={}){const w=mount(WorkspaceSwitcher,{attachTo:document.body,props:{teams:[{id:'team-1',name:'Engineering'}],...props},global:{directives:{tooltip:{}}}});wrappers.push(w);return w;}
describe('WorkspaceSwitcher',()=>{
 // The top-bar variant: a quiet text trigger like the model selector, naming the space.
 it('toolbar: names the space and opens the same picker, kept inside the window',async()=>{window.innerWidth=1000;const w=setup({toolbar:true,modelValue:'team-1'});expect(w.find('.workspace-toolbar-btn').text()).toBe('Engineering');expect(w.find('.workspace-icon').exists()).toBe(false);const rect={left:900,right:980,top:0,bottom:24,width:80,height:24};w.find('.custom-select').element.getBoundingClientRect=()=>rect;await w.find('.workspace-toolbar-btn').trigger('click');await flushPromises();expect([...document.querySelectorAll('[role=option]')].map(o=>o.textContent.trim())).toContain('Manage spaces…');const menu=document.querySelector('.options-container');expect(menu.style.width).toBe('240px');expect(parseFloat(menu.style.left)+240).toBeLessThanOrEqual(1000-8);expect(w.emitted('refresh')).toBeTruthy();});
 it('toolbar: Personal when no team is chosen',()=>{const w=setup({toolbar:true});expect(w.find('.workspace-toolbar-btn').text()).toBe('Personal');expect(w.find('.workspace-toolbar-btn i').classes()).toContain('fa-user');});
 it('derives the visible current name from identity, not a separate stale label',async()=>{const w=setup();expect(w.find('.selected-label').text()).toBe('Personal');await w.setProps({modelValue:'team-1'});expect(w.find('.selected-label').text()).toBe('Engineering');expect(w.attributes('class')).toContain('workspace-switcher');});
 it('opens the compact picker without triggering the outside-click close',async()=>{const w=setup({compact:true});await w.find('.workspace-icon').trigger('click');await flushPromises();expect([...document.querySelectorAll('[role=option]')].map(o=>o.textContent.trim())).toEqual(['Personal','Personal','Team spaces','Engineering','Manage spaces…']);expect(document.querySelector('.options-container').style.width).toBe('240px');const option=[...document.querySelectorAll('[role=option]')].find(e=>e.textContent.includes('Engineering'));option.click();await flushPromises();expect(w.emitted('select').at(-1)).toEqual(['team-1']);await new Promise(resolve=>setTimeout(resolve,60));await flushPromises();expect(document.querySelector('[role=option]')).toBeNull();});
 it('offers joining a team space when there is none, as an action rather than a space',async()=>{const w=setup({teams:[]});await w.find('.selected').trigger('click');await flushPromises();const options=[...document.querySelectorAll('[role=option]')];expect(options.map(o=>o.textContent.trim())).toEqual(['Personal','Personal','Join or create a team space…']);options[2].click();await flushPromises();expect(w.emitted('select').at(-1)).toEqual(['__manage']);});
 it('shows unread from the other spaces, never the one you are in',async()=>{const w=setup({modelValue:'team-1',unread:{'':4,'team-1':7}});await w.find('.selected').trigger('click');await flushPromises();const labels=[...document.querySelectorAll('[role=option]')].map(o=>o.textContent.trim());expect(labels).toContain('Personal · 4');expect(labels).toContain('Engineering');});
 // Each instance is its own site, so the account differs per instance; measured: a switch opened
 // bravo as a different account and nothing said so. Headings group the two kinds of space.
 it('says who is signed in, groups Personal and Team spaces, and details each team space',async()=>{const w=setup({account:'n@gmail.test',personalHint:'goku',modelValue:'team-1',teams:[{id:'team-1',name:'bravo',role:'owner',seats:{used:2,total:3}},{id:'team-2',name:'delta',role:'member',seats:{used:1,total:3}}]});await w.find('.selected').trigger('click');await flushPromises();const options=[...document.querySelectorAll('[role=option]')];expect(options.map(o=>o.textContent.trim())).toEqual(['Signed in as n@gmail.test','Personal','Personal · goku','Team spaces','bravo · owner · 2 members','delta · 1 member','Manage spaces…']);for(const index of [0,1,3])options[index].click();await flushPromises();expect(w.emitted('select')).toBeUndefined();options[2].click();await flushPromises();expect(w.emitted('select').at(-1)).toEqual(['']);});
 it('announces scope in the compact button and shows retry on load failure',async()=>{const w=setup({modelValue:'team-1',compact:true});expect(w.find('.workspace-icon').attributes('aria-label')).toContain('Engineering');await w.setProps({compact:false,error:'Cannot load teams.'});expect(w.find('[role=status]').text()).toContain('Cannot load teams.');await w.find('[role=status] button').trigger('click');expect(w.emitted('refresh')).toHaveLength(1)});
});
