import {describe,it,expect,vi} from 'vitest';
import {createCodexVoiceController} from './codexVoiceController.js';
import {parseCodexEvent,codexContextFrames} from './codexVoiceProtocol.js';
import {createRequestVoiceBridge} from './requestVoiceBridge.js';
const SDP='v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\n';
const wait=()=>new Promise(r=>setTimeout(r,0));
const delegation=id=>JSON.stringify({type:'delegation.created',item:{type:'delegation',target:'client',id,content:[{type:'input_text',text:'Check the status.'}]}});
const final=id=>JSON.stringify({type:'turn.done',turn:{id,role:'user',transcript:'Check the status.'}});
function fixture(submitTurn=vi.fn(async()=>({accepted:false}))) {
 let peer;const track={stop:vi.fn()},mic={getTracks:()=>[track]},audio={play:vi.fn(async()=>{}),pause:vi.fn()},states=[],errors=[];
 class Peer{constructor(){peer=this;this.connectionState='new';}addTrack(){}createDataChannel(){return this.channel={readyState:'connecting',send:vi.fn(),close:vi.fn()};}async createOffer(){return {sdp:SDP,type:'offer'};}async setLocalDescription(o){this.localDescription=o;}async setRemoteDescription(){this.channel.readyState='open';this.channel.onopen();}close(){this.connectionState='closed';}}
 const getUserMedia=vi.fn(async()=>mic),fetchImpl=vi.fn(async()=>new Response(SDP));
 const c=createCodexVoiceController({apiBase:'/api',getToken:()=> 'fixture',submitTurn,Peer,getUserMedia,makeAudio:()=>audio,fetchImpl,onState:s=>states.push(s),onError:e=>errors.push(e)});
 return {c,submitTurn,track,audio,states,errors,getUserMedia,fetchImpl,get peer(){return peer;}};
}
describe('native Codex frontend production modules',()=>{
 it('protocol differentiates observations and delegation',()=>{expect(parseCodexEvent(delegation('d'))).toEqual({type:'delegation',id:'d',text:'Check the status.'});expect(parseCodexEvent('{"type":"turn.done","turn":{"role":"user","transcript":"hello"}}')).toMatchObject({final:true,role:'user'});});
 it('context splitting preserves UTF8 text',()=>{const text='🌍 Hallo '.repeat(200);const frames=codexContextFrames('d','speakable',text);expect(frames.map(f=>f.content[0].text).join('')).toBe(text);for(const f of frames)expect(new TextEncoder().encode(f.content[0].text).length).toBeLessThanOrEqual(500);});
 it('invalid protocol errors are sanitized by controller',async()=>{const f=fixture();await f.c.start();f.peer.channel.onmessage({data:'bad json'});await wait();expect(f.errors).toContain('voice_protocol_error');expect(f.c.active).toBe(false);expect(f.track.stop).toHaveBeenCalled();});
 it('connects using selected provider and no credential in URL',async()=>{const f=fixture();expect(await f.c.start({provider:'openai-codex-2',voice:'cove'})).toBe(true);expect(f.fetchImpl.mock.calls[0][0]).toContain('provider=openai-codex-2');expect(f.fetchImpl.mock.calls[0][0]).not.toContain('fixture');f.c.stop();});
 it('stop closes tracks, peer, channel and playback',async()=>{const f=fixture();await f.c.start();const peer=f.peer;f.c.stop();expect(f.track.stop).toHaveBeenCalledTimes(1);expect(peer.channel.close).toHaveBeenCalled();expect(f.audio.pause).toHaveBeenCalled();expect(peer.connectionState).toBe('closed');});
 it('denied permission never calls provider',async()=>{const f=fixture();f.getUserMedia.mockRejectedValue(Object.assign(new Error(),{name:'NotAllowedError'}));expect(await f.c.start()).toBe(false);expect(f.fetchImpl).not.toHaveBeenCalled();expect(f.errors).toContain('voice_microphone_denied');});
 it('entitlement denial does not try another provider',async()=>{const f=fixture();f.fetchImpl.mockResolvedValue(new Response('',{status:403}));expect(await f.c.start()).toBe(false);expect(f.fetchImpl).toHaveBeenCalledTimes(1);expect(f.errors).toContain('voice_entitlement_denied');});
 it('duplicate final turn dispatches once',async()=>{const f=fixture();await f.c.start();f.peer.channel.onmessage({data:final('d1')});await wait();f.peer.channel.onmessage({data:final('d1')});await wait();expect(f.submitTurn).toHaveBeenCalledTimes(1);f.c.stop();});
 it('speech needs matching accepted server message',async()=>{const submit=vi.fn(async({onAccepted,onSpeech})=>{onSpeech('No receipt yet.','m');onAccepted({accepted:true,conversationId:'c',assistantMessageId:'m'});onSpeech('Wrong message.','x');onSpeech('Verified result.','m');return {accepted:true};});const f=fixture(submit);await f.c.start();f.peer.channel.onmessage({data:final('d1')});await wait();const out=f.peer.channel.send.mock.calls.map(([x])=>JSON.parse(x));expect(out).toHaveLength(1);expect(out[0].content[0].text).toBe('Verified result.');f.c.stop();});
 it('late callback after stop cannot narrate',async()=>{let callbacks,resolve;const f=fixture(vi.fn(args=>{callbacks=args;return new Promise(r=>resolve=r);}));await f.c.start();const channel=f.peer.channel;channel.onmessage({data:final('d')});await wait();f.c.stop();callbacks.onAccepted({accepted:true,conversationId:'c',assistantMessageId:'m'});callbacks.onSpeech('late','m');resolve({accepted:true});await wait();expect(channel.send).not.toHaveBeenCalled();});
 it('request bridge ignores wrong stream message and screen detail',()=>{const onAccepted=vi.fn(),onSpeech=vi.fn();const b=createRequestVoiceBridge({onAccepted,onSpeech});b.event('conversation_started',{conversationId:'c'});b.event('assistant_message',{id:'m'});b.event('content_delta',{assistantMessageId:'wrong',delta:'Wrong. '});b.event('content_delta',{assistantMessageId:'m',delta:'The answer is ready.\n\nScreen-only detail.'});b.event('done');expect(b.finish()).toMatchObject({accepted:true,assistantMessageId:'m',identityKind:'server-message'});expect(onSpeech.mock.calls.map(x=>x[0]).join(' ')).not.toContain('Wrong');expect(onSpeech.mock.calls.map(x=>x[0]).join(' ')).not.toContain('Screen-only');});
 it('request error remains unconfirmed',()=>{const b=createRequestVoiceBridge();b.event('error');expect(b.finish()).toMatchObject({accepted:false,reason:'request_failed'});});
});
