import {it,expect,vi} from 'vitest';
import {createCodexFinalTurnBridge} from './codexFinalTurnBridge.js';
const final=id=>({type:'transcript',role:'user',final:true,id,text:'hello'});
const receipt={accepted:true,conversationId:'c',assistantMessageId:'m'};
function setup(){let resolve,args;const emit=vi.fn(),onError=vi.fn(),setPlaybackAllowed=vi.fn();const submitTurn=vi.fn(a=>{args=a;return new Promise(r=>resolve=r);});const b=createCodexFinalTurnBridge({submitTurn,emit,onError,setPlaybackAllowed});return {b,emit,onError,setPlaybackAllowed,submitTurn,get args(){return args;},finish(){resolve({accepted:true});}};}
it('native delegation alone never starts a second authoritative path',async()=>{const f=setup();await f.b.handle({type:'delegation',id:'d',text:'hello'});expect(f.submitTurn).not.toHaveBeenCalled();});
it('late repeated final does not invalidate speech',async()=>{const f=setup();await f.b.handle({type:'user-turn-start',id:'u1'});const pending=f.b.handle(final('u1'));await f.b.handle(final('u1'));f.args.onAccepted(receipt);f.args.onSpeech('hello','m');expect(f.emit).toHaveBeenCalledTimes(1);expect(f.emit).toHaveBeenCalledWith('hello',null);f.finish();await pending;});
it('new native turn invalidates prior speech before its transcript is final',async()=>{const f=setup();const pending=f.b.handle(final('u1'));f.args.onAccepted(receipt);await f.b.handle({type:'user-turn-start',id:'u2'});f.args.onSpeech('stale','m');expect(f.emit).not.toHaveBeenCalled();f.finish();await pending;});
it('old final after new turn does not dispatch',async()=>{const f=setup();await f.b.handle({type:'user-turn-start',id:'u1'});await f.b.handle({type:'user-turn-start',id:'u2'});await f.b.handle(final('u1'));expect(f.submitTurn).not.toHaveBeenCalled();expect(f.onError).toHaveBeenCalledWith('voice_stale_final');});
it('repeated words in distinct completed turns are allowed',async()=>{const f=setup();let p=f.b.handle(final('u1'));f.args.onAccepted(receipt);f.finish();await p;p=f.b.handle(final('u2'));expect(f.submitTurn).toHaveBeenCalledTimes(2);f.finish();await p;});
it('missing native final identity refuses dispatch',async()=>{const f=setup();await expect(f.b.handle(final(undefined))).rejects.toThrow('voice_final_missing_id');expect(f.submitTurn).not.toHaveBeenCalled();});
it('close preserves already running task but forbids speech',async()=>{const f=setup();const p=f.b.handle(final('u1'));f.b.close();f.args.onAccepted(receipt);f.args.onSpeech('late','m');expect(f.emit).not.toHaveBeenCalled();f.finish();await p;await f.b.handle(final('u2'));expect(f.submitTurn).toHaveBeenCalledTimes(1);});
