import { describe, it, expect, vi } from 'vitest';
import { deflateSync } from 'node:zlib';
import { generateCodexImage } from './codexImageTransport.js';
function chunk(type,payload){const data=Buffer.concat([Buffer.from(type),payload]);let crc=0xffffffff;for(const v of data){crc^=v;for(let i=0;i<8;i++)crc=(crc>>>1)^(0xedb88320&-(crc&1));}const b=Buffer.alloc(payload.length+12);b.writeUInt32BE(payload.length,0);data.copy(b,4);b.writeUInt32BE((crc^0xffffffff)>>>0,b.length-4);return b;}
const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(1,0);ihdr.writeUInt32BE(1,4);ihdr[8]=8;ihdr[9]=6;
const png=Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(Buffer.from([0,0,128,128,255]))),chunk('IEND',Buffer.alloc(0))]);
const uri='data:image/png;base64,'+png.toString('base64');
const params={provider:'openai-codex',imagePrompt:'synthetic icon'};
function setup(body={data:[{b64_json:png.toString('base64')}],usage:{total_tokens:5}}){const post=vi.fn(()=>({asResponse:async()=>new Response(JSON.stringify(body),{headers:{'x-request-id':'safe-request'}})}));const createClient=vi.fn(async()=>({baseURL:'https://chatgpt.com/backend-api/codex',post}));return {post,createClient};}
describe('bounded native Codex image transport',()=>{
 it('has no fixed model and keeps returned identity unknown',async()=>{const s=setup();const out=await generateCodexImage(params,s);expect(s.post.mock.calls[0][0]).toBe('/images/generations');expect(s.post.mock.calls[0][1].body).not.toHaveProperty('model');expect(s.post.mock.calls[0][1].maxRetries).toBe(0);expect(s.post.mock.calls[0][1].fetchOptions.redirect).toBe('error');expect(out.imageMetadata).toMatchObject({resolvedModel:null,returnedModel:null,latestVerified:false,usage:{total_tokens:5},cost:null});expect(out.generatedImages[0]).toBe(uri);});
 it('preserves account2 factory selection',async()=>{const s=setup();await generateCodexImage({...params,provider:'openai-codex-2'},{...s,userId:'test-user'});expect(s.createClient).toHaveBeenCalledWith('openai-codex-2','test-user');});
 it('uses direct JSON edits with explicit PNG references',async()=>{const s=setup();await generateCodexImage({...params,imageOperation:'Edit',referenceImages:[uri]},s);expect(s.post.mock.calls[0][0]).toBe('/images/edits');expect(s.post.mock.calls[0][1].body.images).toEqual([{image_url:uri}]);});
 it.each([{model:'latest'},{model:'gpt-image-2.5-sunburst'},{numberOfImages:2},{imageOperation:'Variation'},{imageOperation:'Edit'},{referenceImages:[uri]},{imageSize:'1024x1024'},{imageQuality:'max'},{imageStyle:'vivid'},{imagePrompt:''},{referenceImages:'bad'},{imageOperation:'Edit',referenceImages:['https://example.com/img.png']},{imageOperation:'Edit',referenceImages:['data:image/png;base64,AAAA']}])('rejects invalid inputs before client construction %j',async overrides=>{const s=setup();await expect(generateCodexImage({...params,...overrides},s)).rejects.toThrow();expect(s.createClient).not.toHaveBeenCalled();});
 it('preserves unknown usage instead of zero',async()=>{const s=setup({data:[{b64_json:png.toString('base64')}]});expect((await generateCodexImage(params,s)).imageMetadata.usage).toBeNull();});
 it('only records returned model when actually supplied',async()=>{const s=setup({model:'provider-returned',data:[{b64_json:png.toString('base64')}]});expect((await generateCodexImage(params,s)).imageMetadata.returnedModel).toBe('provider-returned');});
 it.each([401,403,429,500])('reports %i without retry and redacts error bodies',async status=>{const s=setup();s.post.mockImplementation(()=>({asResponse:async()=>{throw Object.assign(new Error('private secret'),{status});}}));await expect(generateCodexImage(params,s)).rejects.toThrow(/not retried/);expect(s.post).toHaveBeenCalledTimes(1);try{await generateCodexImage(params,s);}catch(e){expect(e.message).not.toContain('private secret');}});
 it.each([{data:[]},{data:[{b64_json:'AAAA'}]},{data:[{b64_json:png.toString('base64').slice(0,-4)+'AAAA'}]},{data:[{b64_json:png.toString('base64')},{b64_json:png.toString('base64')}]}])('rejects invalid response %j',async body=>{await expect(generateCodexImage(params,setup(body))).rejects.toThrow(/validation/);});
 it('does not promote a returned label into verified identity',async()=>{const out=await generateCodexImage(params,setup({model:'claimed-engine',data:[{b64_json:png.toString('base64')}]}));expect(out.imageMetadata.returnedModel).toBe('claimed-engine');expect(out.imageMetadata.modelIdentityVerified).toBe(false);});
 it('honors abort at iterator completion',async()=>{const s=setup(),c=new AbortController();s.post.mockImplementation(()=>({asResponse:async()=>({ok:true,headers:new Headers(),body:{async *[Symbol.asyncIterator](){yield Buffer.from(JSON.stringify({data:[{b64_json:png.toString('base64')}]}));c.abort();}}})}));await expect(generateCodexImage(params,{...s,signal:c.signal})).rejects.toThrow(/cancelled/);});
 it('bounds a stalled response iterator',async()=>{const s=setup();s.post.mockImplementation(()=>({asResponse:async()=>({ok:true,headers:new Headers(),body:{[Symbol.asyncIterator](){return {next:()=>new Promise(()=>{})};}}})}));await expect(generateCodexImage(params,{...s,timeoutMs:10})).rejects.toThrow(/deadline/);},500);
 it('does not dispatch when already aborted',async()=>{const s=setup();const c=new AbortController();c.abort();await expect(generateCodexImage(params,{...s,signal:c.signal})).rejects.toThrow(/cancelled/);expect(s.post).not.toHaveBeenCalled();});
 it('rejects untrusted destinations before POST',async()=>{const s=setup();s.createClient.mockResolvedValue({baseURL:'https://example.com',post:s.post});await expect(generateCodexImage(params,s)).rejects.toThrow();expect(s.post).not.toHaveBeenCalled();});
 it('bounds pending asynchronous client initialization',async()=>{const s=setup();s.createClient.mockImplementation(()=>new Promise(()=>{}));await expect(generateCodexImage(params,{...s,timeoutMs:10})).rejects.toThrow(/deadline/);expect(s.post).not.toHaveBeenCalled();},500);
 it('cancels while awaiting client initialization',async()=>{const s=setup();s.createClient.mockImplementation(()=>new Promise(()=>{}));const c=new AbortController();const run=generateCodexImage(params,{...s,signal:c.signal});c.abort();await expect(run).rejects.toThrow(/cancelled/);expect(s.post).not.toHaveBeenCalled();},500);
});
