import {describe,it,expect,vi,beforeAll,beforeEach} from 'vitest';
import crypto from 'node:crypto';
import {png} from '../../../../tests/fixtures/imagePng.js';
const calls=vi.hoisted(()=>({api:vi.fn(),client:vi.fn(),post:vi.fn(),identity:'account-A'}));
vi.mock('../auth/AuthManager.js',()=>({default:{getConnectedApps:async()=>[],getValidAccessToken:calls.api}}));
vi.mock('../auth/CodexAuthManager.js',()=>({default:{getChatGptAccountId:()=>calls.identity}}));
vi.mock('../ai/LlmService.js',()=>({createLlmClient:calls.client}));
let service,TOOLS,action;
beforeAll(async()=>{vi.stubEnv('AGNT_CODEX_IMAGE_ENABLED','true');const {dbReady}=await import('../../models/database/index.js');await dbReady;service=(await import('./imageSettingsRuntime.js')).imageSettingsService;TOOLS=(await import('../orchestrator/tools.js')).TOOLS;action=(await import('../../tools/library/actions/generate-with-ai-llm.js')).default;});
beforeEach(()=>{vi.clearAllMocks();calls.identity='account-A';calls.api.mockImplementation(()=>{throw Error('API route forbidden');});calls.post.mockImplementation(()=>({asResponse:async()=>new Response(JSON.stringify({data:[{b64_json:png.toString('base64')}],usage:{total_tokens:12}}))}));calls.client.mockImplementation(async()=>({baseURL:'https://chatgpt.com/backend-api/codex',defaultHeaders:()=>({'chatgpt-account-id':calls.identity}),post:calls.post}));});
async function configure(u,allow){const {settings}=await service.read(u);await service.update(u,{expectedRevision:settings.revision,selectedConnectionId:'openai-codex',consent:{connectionId:'openai-codex',allow}});}
const generate=(u,extra={})=>TOOLS.generate_image.execute({prompt:'fixture',...extra},null,{userId:u,useImageSettings:true,provider:'gemini',imageData:[{type:'image/png',data:png.toString('base64')}] }).then(JSON.parse);
describe('Feature: independent stored Codex consent reaches actual native image transport',()=>{
 it('Given consent and Gemini text, Then generate through Codex with no model field or API fallback',async()=>{const u=crypto.randomUUID();await configure(u,true);const out=await generate(u);expect(out.success).toBe(true);expect(calls.post).toHaveBeenCalledOnce();expect(calls.post.mock.calls[0][1].body).not.toHaveProperty('model');expect(out.imageMetadata.returnedModel).toBeNull();expect(calls.api).not.toHaveBeenCalled();});
 it('Given explicit selected reference, Then native Edit preserves the reference',async()=>{const u=crypto.randomUUID();await configure(u,true);const out=await generate(u,{operation:'edit',referenceHandles:['upload:0']});expect(out.success).toBe(true);expect(calls.post.mock.calls[0][0]).toBe('/images/edits');expect(calls.post.mock.calls[0][1].body.images[0].image_url).toBe('data:image/png;base64,'+png.toString('base64'));});
 it('Given no consent, Then direct tool and workflow cannot bypass it',async()=>{const u=crypto.randomUUID();await configure(u,false);expect((await generate(u)).success).toBe(false);const out=await action.execute({mode:'Image Generation',provider:'openai-codex',imagePrompt:'fixture'},{},{userId:u});expect(out.error).toMatch(/consent/);expect(calls.client).not.toHaveBeenCalled();expect(calls.post).not.toHaveBeenCalled();});
 it('Given consent revoked during client initialization, Then zero image POSTs',async()=>{const u=crypto.randomUUID();await configure(u,true);calls.client.mockImplementation(async()=>{const {settings}=await service.read(u);await service.update(u,{expectedRevision:settings.revision,consent:{connectionId:'openai-codex',allow:false}});return {baseURL:'https://chatgpt.com/backend-api/codex',defaultHeaders:()=>({'chatgpt-account-id':'account-A'}),post:calls.post};});expect((await generate(u)).success).toBe(false);expect(calls.post).not.toHaveBeenCalled();});
 it('Given account rebound after consent, Then old grant fails',async()=>{const u=crypto.randomUUID();await configure(u,true);calls.identity='account-B';expect((await generate(u)).success).toBe(false);expect(calls.post).not.toHaveBeenCalled();});
 it('Given factory returns a different account, Then affinity check prevents dispatch',async()=>{const u=crypto.randomUUID();await configure(u,true);calls.client.mockResolvedValue({baseURL:'https://chatgpt.com/backend-api/codex',defaultHeaders:()=>({'chatgpt-account-id':'account-B'}),post:calls.post});expect((await generate(u)).success).toBe(false);expect(calls.post).not.toHaveBeenCalled();});
});
