import {describe,it,expect,vi} from 'vitest';
import express from 'express';
import {createImageSettingsHandlers} from './imageSettingsHandlers.js';
import {createImageSettingsService} from './imageSettingsService.js';
import {initialSettings} from './imageSettingsContract.js';
function setup(){let state=initialSettings();const c={id:'openai',provider:'openai',ownerId:'u',binding:'api-slot',connected:true,operations:['generate','edit'],requiresConsent:false};const store={read:async()=>state,compareAndSwap:async(u,r,n)=>{if(state.revision!==r)throw Object.assign(Error('conflict'),{code:'IMAGE_SETTINGS_CONFLICT'});state=n;return n;}};return {service:createImageSettingsService({store,listConnections:async()=>[c]}),c};}
describe('Feature: production image settings service and HTTP handlers',()=>{
 it('Given a pending request, When account disconnects, Then pre-dispatch fails',async()=>{const {service,c}=setup();await service.update('u',{expectedRevision:0,selectedConnectionId:'openai'});const p=await service.prepare('u',{operation:'generate'});c.connected=false;await expect(p.beforeDispatch()).rejects.toThrow(/unavailable/);});
 it('Given later option changes, Then a prepared request retains its selection',async()=>{const {service}=setup();await service.update('u',{expectedRevision:0,selectedConnectionId:'openai'});const p=await service.prepare('u',{operation:'generate'});await service.update('u',{expectedRevision:1,options:{connectionId:'openai',value:{model:'latest-fast'}}});await p.beforeDispatch();expect(p.request.model).toBe('latest');});
 it('Given anonymous request, Then no stored settings are read',async()=>{const service={read:vi.fn()};const h=createImageSettingsHandlers(service);const res={status:vi.fn().mockReturnThis(),json:vi.fn()};await h.get({user:{id:'anonymous',isAuthenticated:false}},res);expect(res.status).toHaveBeenCalledWith(401);expect(service.read).not.toHaveBeenCalled();});
 it('Given authenticated save, Then revision persists and private binding is not returned by GET',async()=>{const {service}=setup();await service.update('u',{expectedRevision:0,selectedConnectionId:'openai',options:{connectionId:'openai',value:{model:'latest-fast'}}});const out=await service.read('u');expect(out.settings.revision).toBe(1);expect(out.connections[0]).not.toHaveProperty('binding');});
 it('Given settings choose OpenAI, Then unrelated text provider cannot change dispatch',async()=>{const {service}=setup();await service.update('u',{expectedRevision:0,selectedConnectionId:'openai'});const p=await service.prepare('u',{operation:'generate'});expect(p.request.provider).toBe('openai');await p.beforeDispatch();await expect(p.beforeDispatch()).rejects.toThrow(/Duplicate/);});
 it('Given no default, Then no automatic API fallback',async()=>{const {service}=setup();await expect(service.prepare('u',{operation:'generate'})).rejects.toThrow(/configured/);});
 it('Given persisted default, Then tool provider/model substitution is rejected',async()=>{const {service}=setup();await service.update('u',{expectedRevision:0,selectedConnectionId:'openai'});await expect(service.prepare('u',{operation:'generate',provider:'gemini'})).rejects.toThrow(/overridden/);await expect(service.prepare('u',{operation:'generate',model:'other'})).rejects.toThrow(/overridden/);});
 it('Given concurrent dispatch checks, Then only one wins',async()=>{const {service}=setup();await service.update('u',{expectedRevision:0,selectedConnectionId:'openai'});const p=await service.prepare('u',{operation:'generate'});expect((await Promise.allSettled([p.beforeDispatch(),p.beforeDispatch()])).filter(r=>r.status==='fulfilled')).toHaveLength(1);});
 it('Given stale revision, Then HTTP409 not a silent overwrite',async()=>{const {service}=setup();await service.update('u',{expectedRevision:0,selectedConnectionId:'openai'});const h=createImageSettingsHandlers(service);const res={status:vi.fn().mockReturnThis(),json:vi.fn()};await h.put({user:{id:'u',isAuthenticated:true},headers:{},body:{expectedRevision:0,selectedConnectionId:null}},res);expect(res.status).toHaveBeenCalledWith(409);});
});
