import {describe,it,expect} from 'vitest';
import {mount} from '@vue/test-utils';
import LearningBoard from './LearningBoard.vue';
const finding={id:'f',revision:3,state:'detected',capability:'read_file',error_kind:'timeout',occurrences:7,independent_runs:4,candidate:{when:{capability:'read_file',error_kind:'timeout'},action:{type:'retry_read_only',max_retries:1}},candidate_hash:'hash'};
const trial={id:'t',revision:1,state:'watching',candidate:finding.candidate,candidate_hash:'hash',baseline:{eligible:28,failed:7},minimum_samples:20,started_at:Date.now()-86400000,review_due_at:Date.now()+6*86400000};
const snapshot=()=>({settings:{paused:false},findings:[finding],trials:[trial],policies:[],coverage:{events:48,work:12}});
const insight=(id,title='Tighten the prompt')=>({id,title,description:'Shorter system prompt',target_type:'agent',autonomy_decision:'escalate',status:'pending',confidence:.8});
describe('one consolidated Learning page',()=>{
 it('shows meaningful states without legacy parameter controls or creation counters',()=>{const w=mount(LearningBoard,{props:{data:snapshot()}});for(const tab of ['Waiting for you','Needs attention','Being tested','Learned'])expect(w.text()).toContain(tab);expect(w.text()).not.toContain('Min confidence');expect(w.text()).not.toContain('Generate dataset');});
 it('selecting a card hands it to the right panel instead of opening an inline aside',async()=>{const w=mount(LearningBoard,{props:{data:snapshot()}});await w.find('.learning-card').trigger('click');expect(w.find('aside').exists()).toBe(false);expect(w.emitted('select')[0][0]).toMatchObject({id:'f',kind:'finding',revision:3,candidate_hash:'hash'});});
 it('marks the selected card',()=>{const w=mount(LearningBoard,{props:{data:snapshot(),selectedKey:'finding:f'}});expect(w.find('.learning-card.chosen').exists()).toBe(true);});
 it('honestly renders a healthy empty state and pause control',async()=>{const data={settings:{paused:true},findings:[],trials:[],policies:[],coverage:{events:0,work:0}};const w=mount(LearningBoard,{props:{data}});expect(w.text()).toContain('Nothing needs your attention.');await w.find('.pause-button').trigger('click');expect(w.emitted('pause')[0]).toEqual([false]);});
 it('does not render hostile trace text as markup',()=>{const data=snapshot();data.findings[0]={...finding,capability:'<script>alert(1)</script>'};const w=mount(LearningBoard,{props:{data}});expect(w.find('script').exists()).toBe(false);expect(w.text()).toContain('<script>');});
});
describe('Waiting for you: the escalation queue on the Learning page',()=>{
 it('counts exactly what the queue holds, the same list the chat panel counts',()=>{const waiting=[insight('a'),insight('b'),insight('c')];const w=mount(LearningBoard,{props:{data:snapshot(),waiting}});const tab=w.findAll('.tab-button').find(b=>b.text().startsWith('Waiting for you'));expect(tab.find('.tab-count').text()).toBe('3');expect(w.findAll('.queue .row')).toHaveLength(3);});
 it('opens on the queue when anything is waiting, and on Needs attention when nothing is',()=>{expect(mount(LearningBoard,{props:{data:snapshot(),waiting:[insight('a')]}}).find('.queue').exists()).toBe(true);expect(mount(LearningBoard,{props:{data:snapshot()}}).find('.queue').exists()).toBe(false);});
 it('switches to the queue when it fills after load, unless the user already chose a tab',async()=>{const w=mount(LearningBoard,{props:{data:snapshot()}});await w.setProps({waiting:[insight('a')]});expect(w.find('.queue').exists()).toBe(true);const v=mount(LearningBoard,{props:{data:snapshot()}});await v.findAll('.tab-button').find(b=>b.text().startsWith('Being tested')).trigger('click');await v.setProps({waiting:[insight('a')]});expect(v.find('.queue').exists()).toBe(false);});
 it('forwards queue verbs as accept-insights / reject-insights',async()=>{const w=mount(LearningBoard,{props:{data:snapshot(),waiting:[insight('a')]}});const row=w.find('.queue .row');await row.findAll('button').find(b=>b.text()==='Accept').trigger('click');await row.findAll('button').find(b=>b.text()==='Reject').trigger('click');expect(w.emitted('accept-insights')).toEqual([[['a']]]);expect(w.emitted('reject-insights')).toEqual([[['a']]]);});
});
