import {describe,it,expect} from 'vitest';
import {mount} from '@vue/test-utils';
import LearningBoard from './LearningBoard.vue';
const finding={id:'f',revision:3,state:'detected',capability:'read_file',error_kind:'timeout',occurrences:7,independent_runs:4,candidate:{when:{capability:'read_file',error_kind:'timeout'},action:{type:'retry_read_only',max_retries:1}},candidate_hash:'hash'};
const trial={id:'t',revision:1,state:'watching',candidate:finding.candidate,candidate_hash:'hash',baseline:{eligible:28,failed:7},minimum_samples:20,started_at:Date.now()-86400000,review_due_at:Date.now()+6*86400000};
const snapshot=()=>({settings:{paused:false},findings:[finding],trials:[trial],policies:[],coverage:{events:48,work:12}});
describe('one consolidated Learning page',()=>{
 it('shows meaningful states without legacy parameter controls or creation counters',()=>{const w=mount(LearningBoard,{props:{data:snapshot()}});expect(w.text()).toContain('Needs attention');expect(w.text()).toContain('Being tested');expect(w.text()).toContain('Learned');expect(w.text()).not.toContain('Min confidence');expect(w.text()).not.toContain('Generate dataset');});
 it('opens evidence and emits an exact hash-bound approval candidate',async()=>{const w=mount(LearningBoard,{props:{data:snapshot()}});await w.find('.learning-card').trigger('click');expect(w.find('aside').text()).toContain('Independent runs');const button=w.findAll('button').find(b=>b.text()==='Try for 7 days');await button.trigger('click');expect(w.emitted('approve')[0][0]).toMatchObject({id:'f',revision:3,candidate_hash:'hash'});});
 it('shows durable deadline, undo and measured review; never lets an inconclusive result keep a change',async()=>{const data=snapshot();data.trials[0]={...trial,state:'reviewed',result:{verdict:'inconclusive',before:.25,after:null,candidate:{eligible:0},method:'observational_before_after',explanation:'Not enough evidence'}};const w=mount(LearningBoard,{props:{data}});await w.find('.learning-card').trigger('click');expect(w.text()).toContain('Not enough evidence');expect(w.text()).not.toContain('Keep this improvement');});
 it('honestly renders a healthy empty state and pause control',async()=>{const data={settings:{paused:true},findings:[],trials:[],policies:[],coverage:{events:0,work:0}};const w=mount(LearningBoard,{props:{data}});expect(w.text()).toContain('Nothing needs your attention.');await w.find('.pause-button').trigger('click');expect(w.emitted('pause')[0]).toEqual([false]);});
 it('does not render hostile trace text as markup',()=>{const data=snapshot();data.findings[0]={...finding,capability:'<script>alert(1)</script>'};const w=mount(LearningBoard,{props:{data}});expect(w.find('script').exists()).toBe(false);expect(w.text()).toContain('<script>');});
});
